// This file is generated by generator.ts

import { FFI_STRUCTS } from "./ffi_structs.ts";

// --- Version constants ---
export const RAYLIB_VERSION_MAJOR = 5;
export const RAYLIB_VERSION_MINOR = 5;
export const RAYLIB_VERSION_PATCH = 0;
export const RAYLIB_VERSION = "5.5";

const DLL_TYPE = ({
  windows: "raylib.dll",
  linux: "libraylib.so",
  darwin: "libraylib.dylib",
} as Record<string, string>)[Deno.build.os];

export const lib = Deno.dlopen(
  "./blobs/" + DLL_TYPE,
  {
	// Initialize window and OpenGL context
	InitWindow: { parameters: ["i32", "i32", "buffer"], result: "void" },
	// Close window and unload OpenGL context
	CloseWindow: { parameters: [], result: "void" },
	// Check if application should close (KEY_ESCAPE pressed or windows close icon clicked)
	WindowShouldClose: { parameters: [], result: "u8" },
	// Check if window has been initialized successfully
	IsWindowReady: { parameters: [], result: "u8" },
	// Check if window is currently fullscreen
	IsWindowFullscreen: { parameters: [], result: "u8" },
	// Check if window is currently hidden
	IsWindowHidden: { parameters: [], result: "u8" },
	// Check if window is currently minimized
	IsWindowMinimized: { parameters: [], result: "u8" },
	// Check if window is currently maximized
	IsWindowMaximized: { parameters: [], result: "u8" },
	// Check if window is currently focused
	IsWindowFocused: { parameters: [], result: "u8" },
	// Check if window has been resized last frame
	IsWindowResized: { parameters: [], result: "u8" },
	// Check if one specific window flag is enabled
	IsWindowState: { parameters: ["u32"], result: "u8" },
	// Set window configuration state using flags
	SetWindowState: { parameters: ["u32"], result: "void" },
	// Clear window configuration state flags
	ClearWindowState: { parameters: ["u32"], result: "void" },
	// Toggle window state: fullscreen/windowed, resizes monitor to match window resolution
	ToggleFullscreen: { parameters: [], result: "void" },
	// Toggle window state: borderless windowed, resizes window to match monitor resolution
	ToggleBorderlessWindowed: { parameters: [], result: "void" },
	// Set window state: maximized, if resizable
	MaximizeWindow: { parameters: [], result: "void" },
	// Set window state: minimized, if resizable
	MinimizeWindow: { parameters: [], result: "void" },
	// Set window state: not minimized/maximized
	RestoreWindow: { parameters: [], result: "void" },
	// Set icon for window (single image, RGBA 32bit)
	SetWindowIcon: { parameters: [FFI_STRUCTS.Image], result: "void" },
	// Set icon for window (multiple images, RGBA 32bit)
	SetWindowIcons: { parameters: ["buffer", "i32"], result: "void" },
	// Set title for window
	SetWindowTitle: { parameters: ["buffer"], result: "void" },
	// Set window position on screen
	SetWindowPosition: { parameters: ["i32", "i32"], result: "void" },
	// Set monitor for the current window
	SetWindowMonitor: { parameters: ["i32"], result: "void" },
	// Set window minimum dimensions (for FLAG_WINDOW_RESIZABLE)
	SetWindowMinSize: { parameters: ["i32", "i32"], result: "void" },
	// Set window maximum dimensions (for FLAG_WINDOW_RESIZABLE)
	SetWindowMaxSize: { parameters: ["i32", "i32"], result: "void" },
	// Set window dimensions
	SetWindowSize: { parameters: ["i32", "i32"], result: "void" },
	// Set window opacity [0.0f..1.0f]
	SetWindowOpacity: { parameters: ["f32"], result: "void" },
	// Set window focused
	SetWindowFocused: { parameters: [], result: "void" },
	// Get native window handle
	GetWindowHandle: { parameters: [], result: "pointer" },
	// Get current screen width
	GetScreenWidth: { parameters: [], result: "i32" },
	// Get current screen height
	GetScreenHeight: { parameters: [], result: "i32" },
	// Get current render width (it considers HiDPI)
	GetRenderWidth: { parameters: [], result: "i32" },
	// Get current render height (it considers HiDPI)
	GetRenderHeight: { parameters: [], result: "i32" },
	// Get number of connected monitors
	GetMonitorCount: { parameters: [], result: "i32" },
	// Get current monitor where window is placed
	GetCurrentMonitor: { parameters: [], result: "i32" },
	// Get specified monitor position
	GetMonitorPosition: { parameters: ["i32"], result: FFI_STRUCTS.Vector2 },
	// Get specified monitor width (current video mode used by monitor)
	GetMonitorWidth: { parameters: ["i32"], result: "i32" },
	// Get specified monitor height (current video mode used by monitor)
	GetMonitorHeight: { parameters: ["i32"], result: "i32" },
	// Get specified monitor physical width in millimetres
	GetMonitorPhysicalWidth: { parameters: ["i32"], result: "i32" },
	// Get specified monitor physical height in millimetres
	GetMonitorPhysicalHeight: { parameters: ["i32"], result: "i32" },
	// Get specified monitor refresh rate
	GetMonitorRefreshRate: { parameters: ["i32"], result: "i32" },
	// Get window position XY on monitor
	GetWindowPosition: { parameters: [], result: FFI_STRUCTS.Vector2 },
	// Get window scale DPI factor
	GetWindowScaleDPI: { parameters: [], result: FFI_STRUCTS.Vector2 },
	// Get the human-readable, UTF-8 encoded name of the specified monitor
	GetMonitorName: { parameters: ["i32"], result: "buffer" },
	// Set clipboard text content
	SetClipboardText: { parameters: ["buffer"], result: "void" },
	// Get clipboard text content
	GetClipboardText: { parameters: [], result: "buffer" },
	// Get clipboard image
	GetClipboardImage: { parameters: [], result: FFI_STRUCTS.Image },
	// Enable waiting for events on EndDrawing(), no automatic event polling
	EnableEventWaiting: { parameters: [], result: "void" },
	// Disable waiting for events on EndDrawing(), automatic events polling
	DisableEventWaiting: { parameters: [], result: "void" },
	// Shows cursor
	ShowCursor: { parameters: [], result: "void" },
	// Hides cursor
	HideCursor: { parameters: [], result: "void" },
	// Check if cursor is not visible
	IsCursorHidden: { parameters: [], result: "u8" },
	// Enables cursor (unlock cursor)
	EnableCursor: { parameters: [], result: "void" },
	// Disables cursor (lock cursor)
	DisableCursor: { parameters: [], result: "void" },
	// Check if cursor is on the screen
	IsCursorOnScreen: { parameters: [], result: "u8" },
	// Set background color (framebuffer clear color)
	ClearBackground: { parameters: [FFI_STRUCTS.Color], result: "void" },
	// Setup canvas (framebuffer) to start drawing
	BeginDrawing: { parameters: [], result: "void" },
	// End canvas drawing and swap buffers (double buffering)
	EndDrawing: { parameters: [], result: "void" },
	// Begin 2D mode with custom camera (2D)
	BeginMode2D: { parameters: [FFI_STRUCTS.Camera2D], result: "void" },
	// Ends 2D mode with custom camera
	EndMode2D: { parameters: [], result: "void" },
	// Begin 3D mode with custom camera (3D)
	BeginMode3D: { parameters: [FFI_STRUCTS.Camera3D], result: "void" },
	// Ends 3D mode and returns to default 2D orthographic mode
	EndMode3D: { parameters: [], result: "void" },
	// Begin drawing to render texture
	BeginTextureMode: { parameters: [FFI_STRUCTS.RenderTexture], result: "void" },
	// Ends drawing to render texture
	EndTextureMode: { parameters: [], result: "void" },
	// Begin custom shader drawing
	BeginShaderMode: { parameters: [FFI_STRUCTS.Shader], result: "void" },
	// End custom shader drawing (use default shader)
	EndShaderMode: { parameters: [], result: "void" },
	// Begin blending mode (alpha, additive, multiplied, subtract, custom)
	BeginBlendMode: { parameters: ["i32"], result: "void" },
	// End blending mode (reset to default: alpha blending)
	EndBlendMode: { parameters: [], result: "void" },
	// Begin scissor mode (define screen area for following drawing)
	BeginScissorMode: { parameters: ["i32", "i32", "i32", "i32"], result: "void" },
	// End scissor mode
	EndScissorMode: { parameters: [], result: "void" },
	// Begin stereo rendering (requires VR simulator)
	BeginVrStereoMode: { parameters: [FFI_STRUCTS.VrStereoConfig], result: "void" },
	// End stereo rendering (requires VR simulator)
	EndVrStereoMode: { parameters: [], result: "void" },
	// Load VR stereo config for VR simulator device parameters
	LoadVrStereoConfig: { parameters: [FFI_STRUCTS.VrDeviceInfo], result: FFI_STRUCTS.VrStereoConfig },
	// Unload VR stereo config
	UnloadVrStereoConfig: { parameters: [FFI_STRUCTS.VrStereoConfig], result: "void" },
	// Load shader from files and bind default locations
	LoadShader: { parameters: ["buffer", "buffer"], result: FFI_STRUCTS.Shader },
	// Load shader from code strings and bind default locations
	LoadShaderFromMemory: { parameters: ["buffer", "buffer"], result: FFI_STRUCTS.Shader },
	// Check if a shader is valid (loaded on GPU)
	IsShaderValid: { parameters: [FFI_STRUCTS.Shader], result: "u8" },
	// Get shader uniform location
	GetShaderLocation: { parameters: [FFI_STRUCTS.Shader, "buffer"], result: "i32" },
	// Get shader attribute location
	GetShaderLocationAttrib: { parameters: [FFI_STRUCTS.Shader, "buffer"], result: "i32" },
	// Set shader uniform value
	SetShaderValue: { parameters: [FFI_STRUCTS.Shader, "i32", "pointer", "i32"], result: "void" },
	// Set shader uniform value vector
	SetShaderValueV: { parameters: [FFI_STRUCTS.Shader, "i32", "pointer", "i32", "i32"], result: "void" },
	// Set shader uniform value (matrix 4x4)
	SetShaderValueMatrix: { parameters: [FFI_STRUCTS.Shader, "i32", FFI_STRUCTS.Matrix], result: "void" },
	// Set shader uniform value for texture (sampler2d)
	SetShaderValueTexture: { parameters: [FFI_STRUCTS.Shader, "i32", FFI_STRUCTS.Texture], result: "void" },
	// Unload shader from GPU memory (VRAM)
	UnloadShader: { parameters: [FFI_STRUCTS.Shader], result: "void" },
	// Get a ray trace from screen position (i.e mouse)
	GetScreenToWorldRay: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Camera3D], result: FFI_STRUCTS.Ray },
	// Get a ray trace from screen position (i.e mouse) in a viewport
	GetScreenToWorldRayEx: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Camera3D, "i32", "i32"], result: FFI_STRUCTS.Ray },
	// Get the screen space position for a 3d world space position
	GetWorldToScreen: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Camera3D], result: FFI_STRUCTS.Vector2 },
	// Get size position for a 3d world space position
	GetWorldToScreenEx: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Camera3D, "i32", "i32"], result: FFI_STRUCTS.Vector2 },
	// Get the screen space position for a 2d camera world space position
	GetWorldToScreen2D: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Camera2D], result: FFI_STRUCTS.Vector2 },
	// Get the world space position for a 2d camera screen space position
	GetScreenToWorld2D: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Camera2D], result: FFI_STRUCTS.Vector2 },
	// Get camera transform matrix (view matrix)
	GetCameraMatrix: { parameters: [FFI_STRUCTS.Camera3D], result: FFI_STRUCTS.Matrix },
	// Get camera 2d transform matrix
	GetCameraMatrix2D: { parameters: [FFI_STRUCTS.Camera2D], result: FFI_STRUCTS.Matrix },
	// Set target FPS (maximum)
	SetTargetFPS: { parameters: ["i32"], result: "void" },
	// Get time in seconds for last frame drawn (delta time)
	GetFrameTime: { parameters: [], result: "f32" },
	// Get elapsed time in seconds since InitWindow()
	GetTime: { parameters: [], result: "f64" },
	// Get current FPS
	GetFPS: { parameters: [], result: "i32" },
	// Swap back buffer with front buffer (screen drawing)
	SwapScreenBuffer: { parameters: [], result: "void" },
	// Register all input events
	PollInputEvents: { parameters: [], result: "void" },
	// Wait for some time (halt program execution)
	WaitTime: { parameters: ["f64"], result: "void" },
	// Set the seed for the random number generator
	SetRandomSeed: { parameters: ["u32"], result: "void" },
	// Get a random value between min and max (both included)
	GetRandomValue: { parameters: ["i32", "i32"], result: "i32" },
	// Load random values sequence, no values repeated
	LoadRandomSequence: { parameters: ["u32", "i32", "i32"], result: "pointer" },
	// Unload random values sequence
	UnloadRandomSequence: { parameters: ["pointer"], result: "void" },
	// Takes a screenshot of current screen (filename extension defines format)
	TakeScreenshot: { parameters: ["buffer"], result: "void" },
	// Setup init configuration flags (view FLAGS)
	SetConfigFlags: { parameters: ["u32"], result: "void" },
	// Open URL with default system browser (if available)
	OpenURL: { parameters: ["buffer"], result: "void" },
	// Set the current threshold (minimum) log level
	SetTraceLogLevel: { parameters: ["i32"], result: "void" },
	// Internal memory allocator
	MemAlloc: { parameters: ["u32"], result: "pointer" },
	// Internal memory reallocator
	MemRealloc: { parameters: ["pointer", "u32"], result: "pointer" },
	// Internal memory free
	MemFree: { parameters: ["pointer"], result: "void" },
	// Set custom trace log
	SetTraceLogCallback: { parameters: ["function"], result: "void" },
	// Set custom file binary data loader
	SetLoadFileDataCallback: { parameters: ["function"], result: "void" },
	// Set custom file binary data saver
	SetSaveFileDataCallback: { parameters: ["function"], result: "void" },
	// Set custom file text data loader
	SetLoadFileTextCallback: { parameters: ["function"], result: "void" },
	// Set custom file text data saver
	SetSaveFileTextCallback: { parameters: ["function"], result: "void" },
	// Load file data as byte array (read)
	LoadFileData: { parameters: ["buffer", "pointer"], result: "buffer" },
	// Unload file data allocated by LoadFileData()
	UnloadFileData: { parameters: ["buffer"], result: "void" },
	// Save data to file from byte array (write), returns true on success
	SaveFileData: { parameters: ["buffer", "pointer", "i32"], result: "u8" },
	// Export data to code (.h), returns true on success
	ExportDataAsCode: { parameters: ["buffer", "i32", "buffer"], result: "u8" },
	// Load text data from file (read), returns a '\0' terminated string
	LoadFileText: { parameters: ["buffer"], result: "buffer" },
	// Unload file text data allocated by LoadFileText()
	UnloadFileText: { parameters: ["buffer"], result: "void" },
	// Save text data to file (write), string must be '\0' terminated, returns true on success
	SaveFileText: { parameters: ["buffer", "buffer"], result: "u8" },
	// Check if file exists
	FileExists: { parameters: ["buffer"], result: "u8" },
	// Check if a directory path exists
	DirectoryExists: { parameters: ["buffer"], result: "u8" },
	// Check file extension (including point: .png, .wav)
	IsFileExtension: { parameters: ["buffer", "buffer"], result: "u8" },
	// Get file length in bytes (NOTE: GetFileSize() conflicts with windows.h)
	GetFileLength: { parameters: ["buffer"], result: "i32" },
	// Get pointer to extension for a filename string (includes dot: '.png')
	GetFileExtension: { parameters: ["buffer"], result: "buffer" },
	// Get pointer to filename for a path string
	GetFileName: { parameters: ["buffer"], result: "buffer" },
	// Get filename string without extension (uses static string)
	GetFileNameWithoutExt: { parameters: ["buffer"], result: "buffer" },
	// Get full path for a given fileName with path (uses static string)
	GetDirectoryPath: { parameters: ["buffer"], result: "buffer" },
	// Get previous directory path for a given path (uses static string)
	GetPrevDirectoryPath: { parameters: ["buffer"], result: "buffer" },
	// Get current working directory (uses static string)
	GetWorkingDirectory: { parameters: [], result: "buffer" },
	// Get the directory of the running application (uses static string)
	GetApplicationDirectory: { parameters: [], result: "buffer" },
	// Create directories (including full path requested), returns 0 on success
	MakeDirectory: { parameters: ["buffer"], result: "i32" },
	// Change working directory, return true on success
	ChangeDirectory: { parameters: ["buffer"], result: "u8" },
	// Check if a given path is a file or a directory
	IsPathFile: { parameters: ["buffer"], result: "u8" },
	// Check if fileName is valid for the platform/OS
	IsFileNameValid: { parameters: ["buffer"], result: "u8" },
	// Load directory filepaths
	LoadDirectoryFiles: { parameters: ["buffer"], result: FFI_STRUCTS.FilePathList },
	// Load directory filepaths with extension filtering and recursive directory scan. Use 'DIR' in the filter string to include directories in the result
	LoadDirectoryFilesEx: { parameters: ["buffer", "buffer", "u8"], result: FFI_STRUCTS.FilePathList },
	// Unload filepaths
	UnloadDirectoryFiles: { parameters: [FFI_STRUCTS.FilePathList], result: "void" },
	// Check if a file has been dropped into window
	IsFileDropped: { parameters: [], result: "u8" },
	// Load dropped filepaths
	LoadDroppedFiles: { parameters: [], result: FFI_STRUCTS.FilePathList },
	// Unload dropped filepaths
	UnloadDroppedFiles: { parameters: [FFI_STRUCTS.FilePathList], result: "void" },
	// Get file modification time (last write time)
	GetFileModTime: { parameters: ["buffer"], result: "i64" },
	// Compress data (DEFLATE algorithm), memory must be MemFree()
	CompressData: { parameters: ["buffer", "i32", "pointer"], result: "buffer" },
	// Decompress data (DEFLATE algorithm), memory must be MemFree()
	DecompressData: { parameters: ["buffer", "i32", "pointer"], result: "buffer" },
	// Encode data to Base64 string, memory must be MemFree()
	EncodeDataBase64: { parameters: ["buffer", "i32", "pointer"], result: "buffer" },
	// Decode Base64 string data, memory must be MemFree()
	DecodeDataBase64: { parameters: ["buffer", "pointer"], result: "buffer" },
	// Compute CRC32 hash code
	ComputeCRC32: { parameters: ["buffer", "i32"], result: "u32" },
	// Compute MD5 hash code, returns static int[4] (16 bytes)
	ComputeMD5: { parameters: ["buffer", "i32"], result: "pointer" },
	// Compute SHA1 hash code, returns static int[5] (20 bytes)
	ComputeSHA1: { parameters: ["buffer", "i32"], result: "pointer" },
	// Load automation events list from file, NULL for empty list, capacity = MAX_AUTOMATION_EVENTS
	LoadAutomationEventList: { parameters: ["buffer"], result: FFI_STRUCTS.AutomationEventList },
	// Unload automation events list from file
	UnloadAutomationEventList: { parameters: [FFI_STRUCTS.AutomationEventList], result: "void" },
	// Export automation events list as text file
	ExportAutomationEventList: { parameters: [FFI_STRUCTS.AutomationEventList, "buffer"], result: "u8" },
	// Set automation event list to record to
	SetAutomationEventList: { parameters: ["buffer"], result: "void" },
	// Set automation event internal base frame to start recording
	SetAutomationEventBaseFrame: { parameters: ["i32"], result: "void" },
	// Start recording automation events (AutomationEventList must be set)
	StartAutomationEventRecording: { parameters: [], result: "void" },
	// Stop recording automation events
	StopAutomationEventRecording: { parameters: [], result: "void" },
	// Play a recorded automation event
	PlayAutomationEvent: { parameters: [FFI_STRUCTS.AutomationEvent], result: "void" },
	// Check if a key has been pressed once
	IsKeyPressed: { parameters: ["i32"], result: "u8" },
	// Check if a key has been pressed again
	IsKeyPressedRepeat: { parameters: ["i32"], result: "u8" },
	// Check if a key is being pressed
	IsKeyDown: { parameters: ["i32"], result: "u8" },
	// Check if a key has been released once
	IsKeyReleased: { parameters: ["i32"], result: "u8" },
	// Check if a key is NOT being pressed
	IsKeyUp: { parameters: ["i32"], result: "u8" },
	// Get key pressed (keycode), call it multiple times for keys queued, returns 0 when the queue is empty
	GetKeyPressed: { parameters: [], result: "i32" },
	// Get char pressed (unicode), call it multiple times for chars queued, returns 0 when the queue is empty
	GetCharPressed: { parameters: [], result: "i32" },
	// Set a custom key to exit program (default is ESC)
	SetExitKey: { parameters: ["i32"], result: "void" },
	// Check if a gamepad is available
	IsGamepadAvailable: { parameters: ["i32"], result: "u8" },
	// Get gamepad internal name id
	GetGamepadName: { parameters: ["i32"], result: "buffer" },
	// Check if a gamepad button has been pressed once
	IsGamepadButtonPressed: { parameters: ["i32", "i32"], result: "u8" },
	// Check if a gamepad button is being pressed
	IsGamepadButtonDown: { parameters: ["i32", "i32"], result: "u8" },
	// Check if a gamepad button has been released once
	IsGamepadButtonReleased: { parameters: ["i32", "i32"], result: "u8" },
	// Check if a gamepad button is NOT being pressed
	IsGamepadButtonUp: { parameters: ["i32", "i32"], result: "u8" },
	// Get the last gamepad button pressed
	GetGamepadButtonPressed: { parameters: [], result: "i32" },
	// Get gamepad axis count for a gamepad
	GetGamepadAxisCount: { parameters: ["i32"], result: "i32" },
	// Get axis movement value for a gamepad axis
	GetGamepadAxisMovement: { parameters: ["i32", "i32"], result: "f32" },
	// Set internal gamepad mappings (SDL_GameControllerDB)
	SetGamepadMappings: { parameters: ["buffer"], result: "i32" },
	// Set gamepad vibration for both motors (duration in seconds)
	SetGamepadVibration: { parameters: ["i32", "f32", "f32", "f32"], result: "void" },
	// Check if a mouse button has been pressed once
	IsMouseButtonPressed: { parameters: ["i32"], result: "u8" },
	// Check if a mouse button is being pressed
	IsMouseButtonDown: { parameters: ["i32"], result: "u8" },
	// Check if a mouse button has been released once
	IsMouseButtonReleased: { parameters: ["i32"], result: "u8" },
	// Check if a mouse button is NOT being pressed
	IsMouseButtonUp: { parameters: ["i32"], result: "u8" },
	// Get mouse position X
	GetMouseX: { parameters: [], result: "i32" },
	// Get mouse position Y
	GetMouseY: { parameters: [], result: "i32" },
	// Get mouse position XY
	GetMousePosition: { parameters: [], result: FFI_STRUCTS.Vector2 },
	// Get mouse delta between frames
	GetMouseDelta: { parameters: [], result: FFI_STRUCTS.Vector2 },
	// Set mouse position XY
	SetMousePosition: { parameters: ["i32", "i32"], result: "void" },
	// Set mouse offset
	SetMouseOffset: { parameters: ["i32", "i32"], result: "void" },
	// Set mouse scaling
	SetMouseScale: { parameters: ["f32", "f32"], result: "void" },
	// Get mouse wheel movement for X or Y, whichever is larger
	GetMouseWheelMove: { parameters: [], result: "f32" },
	// Get mouse wheel movement for both X and Y
	GetMouseWheelMoveV: { parameters: [], result: FFI_STRUCTS.Vector2 },
	// Set mouse cursor
	SetMouseCursor: { parameters: ["i32"], result: "void" },
	// Get touch position X for touch point 0 (relative to screen size)
	GetTouchX: { parameters: [], result: "i32" },
	// Get touch position Y for touch point 0 (relative to screen size)
	GetTouchY: { parameters: [], result: "i32" },
	// Get touch position XY for a touch point index (relative to screen size)
	GetTouchPosition: { parameters: ["i32"], result: FFI_STRUCTS.Vector2 },
	// Get touch point identifier for given index
	GetTouchPointId: { parameters: ["i32"], result: "i32" },
	// Get number of touch points
	GetTouchPointCount: { parameters: [], result: "i32" },
	// Enable a set of gestures using flags
	SetGesturesEnabled: { parameters: ["u32"], result: "void" },
	// Check if a gesture have been detected
	IsGestureDetected: { parameters: ["u32"], result: "u8" },
	// Get latest detected gesture
	GetGestureDetected: { parameters: [], result: "i32" },
	// Get gesture hold time in seconds
	GetGestureHoldDuration: { parameters: [], result: "f32" },
	// Get gesture drag vector
	GetGestureDragVector: { parameters: [], result: FFI_STRUCTS.Vector2 },
	// Get gesture drag angle
	GetGestureDragAngle: { parameters: [], result: "f32" },
	// Get gesture pinch delta
	GetGesturePinchVector: { parameters: [], result: FFI_STRUCTS.Vector2 },
	// Get gesture pinch angle
	GetGesturePinchAngle: { parameters: [], result: "f32" },
	// Update camera position for selected mode
	UpdateCamera: { parameters: ["buffer", "i32"], result: "void" },
	// Update camera movement/rotation
	UpdateCameraPro: { parameters: ["buffer", FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32"], result: "void" },
	// Set texture and rectangle to be used on shapes drawing
	SetShapesTexture: { parameters: [FFI_STRUCTS.Texture, FFI_STRUCTS.Rectangle], result: "void" },
	// Get texture that is used for shapes drawing
	GetShapesTexture: { parameters: [], result: FFI_STRUCTS.Texture },
	// Get texture source rectangle that is used for shapes drawing
	GetShapesTextureRectangle: { parameters: [], result: FFI_STRUCTS.Rectangle },
	// Draw a pixel using geometry [Can be slow, use with care]
	DrawPixel: { parameters: ["i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a pixel using geometry (Vector version) [Can be slow, use with care]
	DrawPixelV: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a line
	DrawLine: { parameters: ["i32", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a line (using gl lines)
	DrawLineV: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a line (using triangles/quads)
	DrawLineEx: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw lines sequence (using gl lines)
	DrawLineStrip: { parameters: ["buffer", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw line segment cubic-bezier in-out interpolation
	DrawLineBezier: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a color-filled circle
	DrawCircle: { parameters: ["i32", "i32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a piece of a circle
	DrawCircleSector: { parameters: [FFI_STRUCTS.Vector2, "f32", "f32", "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw circle sector outline
	DrawCircleSectorLines: { parameters: [FFI_STRUCTS.Vector2, "f32", "f32", "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a gradient-filled circle
	DrawCircleGradient: { parameters: ["i32", "i32", "f32", FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: "void" },
	// Draw a color-filled circle (Vector version)
	DrawCircleV: { parameters: [FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw circle outline
	DrawCircleLines: { parameters: ["i32", "i32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw circle outline (Vector version)
	DrawCircleLinesV: { parameters: [FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw ellipse
	DrawEllipse: { parameters: ["i32", "i32", "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw ellipse outline
	DrawEllipseLines: { parameters: ["i32", "i32", "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw ring
	DrawRing: { parameters: [FFI_STRUCTS.Vector2, "f32", "f32", "f32", "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw ring outline
	DrawRingLines: { parameters: [FFI_STRUCTS.Vector2, "f32", "f32", "f32", "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a color-filled rectangle
	DrawRectangle: { parameters: ["i32", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a color-filled rectangle (Vector version)
	DrawRectangleV: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a color-filled rectangle
	DrawRectangleRec: { parameters: [FFI_STRUCTS.Rectangle, FFI_STRUCTS.Color], result: "void" },
	// Draw a color-filled rectangle with pro parameters
	DrawRectanglePro: { parameters: [FFI_STRUCTS.Rectangle, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a vertical-gradient-filled rectangle
	DrawRectangleGradientV: { parameters: ["i32", "i32", "i32", "i32", FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: "void" },
	// Draw a horizontal-gradient-filled rectangle
	DrawRectangleGradientH: { parameters: ["i32", "i32", "i32", "i32", FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: "void" },
	// Draw a gradient-filled rectangle with custom vertex colors
	DrawRectangleGradientEx: { parameters: [FFI_STRUCTS.Rectangle, FFI_STRUCTS.Color, FFI_STRUCTS.Color, FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: "void" },
	// Draw rectangle outline
	DrawRectangleLines: { parameters: ["i32", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw rectangle outline with extended parameters
	DrawRectangleLinesEx: { parameters: [FFI_STRUCTS.Rectangle, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw rectangle with rounded edges
	DrawRectangleRounded: { parameters: [FFI_STRUCTS.Rectangle, "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw rectangle lines with rounded edges
	DrawRectangleRoundedLines: { parameters: [FFI_STRUCTS.Rectangle, "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw rectangle with rounded edges outline
	DrawRectangleRoundedLinesEx: { parameters: [FFI_STRUCTS.Rectangle, "f32", "i32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a color-filled triangle (vertex in counter-clockwise order!)
	DrawTriangle: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw triangle outline (vertex in counter-clockwise order!)
	DrawTriangleLines: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a triangle fan defined by points (first vertex is the center)
	DrawTriangleFan: { parameters: ["buffer", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a triangle strip defined by points
	DrawTriangleStrip: { parameters: ["buffer", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a regular polygon (Vector version)
	DrawPoly: { parameters: [FFI_STRUCTS.Vector2, "i32", "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a polygon outline of n sides
	DrawPolyLines: { parameters: [FFI_STRUCTS.Vector2, "i32", "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a polygon outline of n sides with extended parameters
	DrawPolyLinesEx: { parameters: [FFI_STRUCTS.Vector2, "i32", "f32", "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline: Linear, minimum 2 points
	DrawSplineLinear: { parameters: ["buffer", "i32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline: B-Spline, minimum 4 points
	DrawSplineBasis: { parameters: ["buffer", "i32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline: Catmull-Rom, minimum 4 points
	DrawSplineCatmullRom: { parameters: ["buffer", "i32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline: Quadratic Bezier, minimum 3 points (1 control point): [p1, c2, p3, c4...]
	DrawSplineBezierQuadratic: { parameters: ["buffer", "i32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline: Cubic Bezier, minimum 4 points (2 control points): [p1, c2, c3, p4, c5, c6...]
	DrawSplineBezierCubic: { parameters: ["buffer", "i32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline segment: Linear, 2 points
	DrawSplineSegmentLinear: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline segment: B-Spline, 4 points
	DrawSplineSegmentBasis: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline segment: Catmull-Rom, 4 points
	DrawSplineSegmentCatmullRom: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline segment: Quadratic Bezier, 2 points, 1 control point
	DrawSplineSegmentBezierQuadratic: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw spline segment: Cubic Bezier, 2 points, 2 control points
	DrawSplineSegmentBezierCubic: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Get (evaluate) spline point: Linear
	GetSplinePointLinear: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	// Get (evaluate) spline point: B-Spline
	GetSplinePointBasis: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	// Get (evaluate) spline point: Catmull-Rom
	GetSplinePointCatmullRom: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	// Get (evaluate) spline point: Quadratic Bezier
	GetSplinePointBezierQuad: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	// Get (evaluate) spline point: Cubic Bezier
	GetSplinePointBezierCubic: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	// Check collision between two rectangles
	CheckCollisionRecs: { parameters: [FFI_STRUCTS.Rectangle, FFI_STRUCTS.Rectangle], result: "u8" },
	// Check collision between two circles
	CheckCollisionCircles: { parameters: [FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Vector2, "f32"], result: "u8" },
	// Check collision between circle and rectangle
	CheckCollisionCircleRec: { parameters: [FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Rectangle], result: "u8" },
	// Check if circle collides with a line created betweeen two points [p1] and [p2]
	CheckCollisionCircleLine: { parameters: [FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: "u8" },
	// Check if point is inside rectangle
	CheckCollisionPointRec: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Rectangle], result: "u8" },
	// Check if point is inside circle
	CheckCollisionPointCircle: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32"], result: "u8" },
	// Check if point is inside a triangle
	CheckCollisionPointTriangle: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: "u8" },
	// Check if point belongs to line created between two points [p1] and [p2] with defined margin in pixels [threshold]
	CheckCollisionPointLine: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "i32"], result: "u8" },
	// Check if point is within a polygon described by array of vertices
	CheckCollisionPointPoly: { parameters: [FFI_STRUCTS.Vector2, "buffer", "i32"], result: "u8" },
	// Check the collision between two lines defined by two points each, returns collision point by reference
	CheckCollisionLines: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "buffer"], result: "u8" },
	// Get collision rectangle for two rectangles collision
	GetCollisionRec: { parameters: [FFI_STRUCTS.Rectangle, FFI_STRUCTS.Rectangle], result: FFI_STRUCTS.Rectangle },
	// Load image from file into CPU memory (RAM)
	LoadImage: { parameters: ["buffer"], result: FFI_STRUCTS.Image },
	// Load image from RAW file data
	LoadImageRaw: { parameters: ["buffer", "i32", "i32", "i32", "i32"], result: FFI_STRUCTS.Image },
	// Load image sequence from file (frames appended to image.data)
	LoadImageAnim: { parameters: ["buffer", "pointer"], result: FFI_STRUCTS.Image },
	// Load image sequence from memory buffer
	LoadImageAnimFromMemory: { parameters: ["buffer", "buffer", "i32", "pointer"], result: FFI_STRUCTS.Image },
	// Load image from memory buffer, fileType refers to extension: i.e. '.png'
	LoadImageFromMemory: { parameters: ["buffer", "buffer", "i32"], result: FFI_STRUCTS.Image },
	// Load image from GPU texture data
	LoadImageFromTexture: { parameters: [FFI_STRUCTS.Texture], result: FFI_STRUCTS.Image },
	// Load image from screen buffer and (screenshot)
	LoadImageFromScreen: { parameters: [], result: FFI_STRUCTS.Image },
	// Check if an image is valid (data and parameters)
	IsImageValid: { parameters: [FFI_STRUCTS.Image], result: "u8" },
	// Unload image from CPU memory (RAM)
	UnloadImage: { parameters: [FFI_STRUCTS.Image], result: "void" },
	// Export image data to file, returns true on success
	ExportImage: { parameters: [FFI_STRUCTS.Image, "buffer"], result: "u8" },
	// Export image to memory buffer
	ExportImageToMemory: { parameters: [FFI_STRUCTS.Image, "buffer", "pointer"], result: "buffer" },
	// Export image as code file defining an array of bytes, returns true on success
	ExportImageAsCode: { parameters: [FFI_STRUCTS.Image, "buffer"], result: "u8" },
	// Generate image: plain color
	GenImageColor: { parameters: ["i32", "i32", FFI_STRUCTS.Color], result: FFI_STRUCTS.Image },
	// Generate image: linear gradient, direction in degrees [0..360], 0=Vertical gradient
	GenImageGradientLinear: { parameters: ["i32", "i32", "i32", FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: FFI_STRUCTS.Image },
	// Generate image: radial gradient
	GenImageGradientRadial: { parameters: ["i32", "i32", "f32", FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: FFI_STRUCTS.Image },
	// Generate image: square gradient
	GenImageGradientSquare: { parameters: ["i32", "i32", "f32", FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: FFI_STRUCTS.Image },
	// Generate image: checked
	GenImageChecked: { parameters: ["i32", "i32", "i32", "i32", FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: FFI_STRUCTS.Image },
	// Generate image: white noise
	GenImageWhiteNoise: { parameters: ["i32", "i32", "f32"], result: FFI_STRUCTS.Image },
	// Generate image: perlin noise
	GenImagePerlinNoise: { parameters: ["i32", "i32", "i32", "i32", "f32"], result: FFI_STRUCTS.Image },
	// Generate image: cellular algorithm, bigger tileSize means bigger cells
	GenImageCellular: { parameters: ["i32", "i32", "i32"], result: FFI_STRUCTS.Image },
	// Generate image: grayscale image from text data
	GenImageText: { parameters: ["i32", "i32", "buffer"], result: FFI_STRUCTS.Image },
	// Create an image duplicate (useful for transformations)
	ImageCopy: { parameters: [FFI_STRUCTS.Image], result: FFI_STRUCTS.Image },
	// Create an image from another image piece
	ImageFromImage: { parameters: [FFI_STRUCTS.Image, FFI_STRUCTS.Rectangle], result: FFI_STRUCTS.Image },
	// Create an image from a selected channel of another image (GRAYSCALE)
	ImageFromChannel: { parameters: [FFI_STRUCTS.Image, "i32"], result: FFI_STRUCTS.Image },
	// Create an image from text (default font)
	ImageText: { parameters: ["buffer", "i32", FFI_STRUCTS.Color], result: FFI_STRUCTS.Image },
	// Create an image from text (custom sprite font)
	ImageTextEx: { parameters: [FFI_STRUCTS.Font, "buffer", "f32", "f32", FFI_STRUCTS.Color], result: FFI_STRUCTS.Image },
	// Convert image data to desired format
	ImageFormat: { parameters: ["buffer", "i32"], result: "void" },
	// Convert image to POT (power-of-two)
	ImageToPOT: { parameters: ["buffer", FFI_STRUCTS.Color], result: "void" },
	// Crop an image to a defined rectangle
	ImageCrop: { parameters: ["buffer", FFI_STRUCTS.Rectangle], result: "void" },
	// Crop image depending on alpha value
	ImageAlphaCrop: { parameters: ["buffer", "f32"], result: "void" },
	// Clear alpha channel to desired color
	ImageAlphaClear: { parameters: ["buffer", FFI_STRUCTS.Color, "f32"], result: "void" },
	// Apply alpha mask to image
	ImageAlphaMask: { parameters: ["buffer", FFI_STRUCTS.Image], result: "void" },
	// Premultiply alpha channel
	ImageAlphaPremultiply: { parameters: ["buffer"], result: "void" },
	// Apply Gaussian blur using a box blur approximation
	ImageBlurGaussian: { parameters: ["buffer", "i32"], result: "void" },
	// Apply custom square convolution kernel to image
	ImageKernelConvolution: { parameters: ["buffer", "pointer", "i32"], result: "void" },
	// Resize image (Bicubic scaling algorithm)
	ImageResize: { parameters: ["buffer", "i32", "i32"], result: "void" },
	// Resize image (Nearest-Neighbor scaling algorithm)
	ImageResizeNN: { parameters: ["buffer", "i32", "i32"], result: "void" },
	// Resize canvas and fill with color
	ImageResizeCanvas: { parameters: ["buffer", "i32", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Compute all mipmap levels for a provided image
	ImageMipmaps: { parameters: ["buffer"], result: "void" },
	// Dither image data to 16bpp or lower (Floyd-Steinberg dithering)
	ImageDither: { parameters: ["buffer", "i32", "i32", "i32", "i32"], result: "void" },
	// Flip image vertically
	ImageFlipVertical: { parameters: ["buffer"], result: "void" },
	// Flip image horizontally
	ImageFlipHorizontal: { parameters: ["buffer"], result: "void" },
	// Rotate image by input angle in degrees (-359 to 359)
	ImageRotate: { parameters: ["buffer", "i32"], result: "void" },
	// Rotate image clockwise 90deg
	ImageRotateCW: { parameters: ["buffer"], result: "void" },
	// Rotate image counter-clockwise 90deg
	ImageRotateCCW: { parameters: ["buffer"], result: "void" },
	// Modify image color: tint
	ImageColorTint: { parameters: ["buffer", FFI_STRUCTS.Color], result: "void" },
	// Modify image color: invert
	ImageColorInvert: { parameters: ["buffer"], result: "void" },
	// Modify image color: grayscale
	ImageColorGrayscale: { parameters: ["buffer"], result: "void" },
	// Modify image color: contrast (-100 to 100)
	ImageColorContrast: { parameters: ["buffer", "f32"], result: "void" },
	// Modify image color: brightness (-255 to 255)
	ImageColorBrightness: { parameters: ["buffer", "i32"], result: "void" },
	// Modify image color: replace color
	ImageColorReplace: { parameters: ["buffer", FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: "void" },
	// Load color data from image as a Color array (RGBA - 32bit)
	LoadImageColors: { parameters: [FFI_STRUCTS.Image], result: "buffer" },
	// Load colors palette from image as a Color array (RGBA - 32bit)
	LoadImagePalette: { parameters: [FFI_STRUCTS.Image, "i32", "pointer"], result: "buffer" },
	// Unload color data loaded with LoadImageColors()
	UnloadImageColors: { parameters: ["buffer"], result: "void" },
	// Unload colors palette loaded with LoadImagePalette()
	UnloadImagePalette: { parameters: ["buffer"], result: "void" },
	// Get image alpha border rectangle
	GetImageAlphaBorder: { parameters: [FFI_STRUCTS.Image, "f32"], result: FFI_STRUCTS.Rectangle },
	// Get image pixel color at (x, y) position
	GetImageColor: { parameters: [FFI_STRUCTS.Image, "i32", "i32"], result: FFI_STRUCTS.Color },
	// Clear image background with given color
	ImageClearBackground: { parameters: ["buffer", FFI_STRUCTS.Color], result: "void" },
	// Draw pixel within an image
	ImageDrawPixel: { parameters: ["buffer", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw pixel within an image (Vector version)
	ImageDrawPixelV: { parameters: ["buffer", FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw line within an image
	ImageDrawLine: { parameters: ["buffer", "i32", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw line within an image (Vector version)
	ImageDrawLineV: { parameters: ["buffer", FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a line defining thickness within an image
	ImageDrawLineEx: { parameters: ["buffer", FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a filled circle within an image
	ImageDrawCircle: { parameters: ["buffer", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a filled circle within an image (Vector version)
	ImageDrawCircleV: { parameters: ["buffer", FFI_STRUCTS.Vector2, "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw circle outline within an image
	ImageDrawCircleLines: { parameters: ["buffer", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw circle outline within an image (Vector version)
	ImageDrawCircleLinesV: { parameters: ["buffer", FFI_STRUCTS.Vector2, "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw rectangle within an image
	ImageDrawRectangle: { parameters: ["buffer", "i32", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw rectangle within an image (Vector version)
	ImageDrawRectangleV: { parameters: ["buffer", FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw rectangle within an image
	ImageDrawRectangleRec: { parameters: ["buffer", FFI_STRUCTS.Rectangle, FFI_STRUCTS.Color], result: "void" },
	// Draw rectangle lines within an image
	ImageDrawRectangleLines: { parameters: ["buffer", FFI_STRUCTS.Rectangle, "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw triangle within an image
	ImageDrawTriangle: { parameters: ["buffer", FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw triangle with interpolated colors within an image
	ImageDrawTriangleEx: { parameters: ["buffer", FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color, FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: "void" },
	// Draw triangle outline within an image
	ImageDrawTriangleLines: { parameters: ["buffer", FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a triangle fan defined by points within an image (first vertex is the center)
	ImageDrawTriangleFan: { parameters: ["buffer", "buffer", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a triangle strip defined by points within an image
	ImageDrawTriangleStrip: { parameters: ["buffer", "buffer", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a source image within a destination image (tint applied to source)
	ImageDraw: { parameters: ["buffer", FFI_STRUCTS.Image, FFI_STRUCTS.Rectangle, FFI_STRUCTS.Rectangle, FFI_STRUCTS.Color], result: "void" },
	// Draw text (using default font) within an image (destination)
	ImageDrawText: { parameters: ["buffer", "buffer", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw text (custom sprite font) within an image (destination)
	ImageDrawTextEx: { parameters: ["buffer", FFI_STRUCTS.Font, "buffer", FFI_STRUCTS.Vector2, "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Load texture from file into GPU memory (VRAM)
	LoadTexture: { parameters: ["buffer"], result: FFI_STRUCTS.Texture },
	// Load texture from image data
	LoadTextureFromImage: { parameters: [FFI_STRUCTS.Image], result: FFI_STRUCTS.Texture },
	// Load cubemap from image, multiple image cubemap layouts supported
	LoadTextureCubemap: { parameters: [FFI_STRUCTS.Image, "i32"], result: FFI_STRUCTS.Texture },
	// Load texture for rendering (framebuffer)
	LoadRenderTexture: { parameters: ["i32", "i32"], result: FFI_STRUCTS.RenderTexture },
	// Check if a texture is valid (loaded in GPU)
	IsTextureValid: { parameters: [FFI_STRUCTS.Texture], result: "u8" },
	// Unload texture from GPU memory (VRAM)
	UnloadTexture: { parameters: [FFI_STRUCTS.Texture], result: "void" },
	// Check if a render texture is valid (loaded in GPU)
	IsRenderTextureValid: { parameters: [FFI_STRUCTS.RenderTexture], result: "u8" },
	// Unload render texture from GPU memory (VRAM)
	UnloadRenderTexture: { parameters: [FFI_STRUCTS.RenderTexture], result: "void" },
	// Update GPU texture with new data
	UpdateTexture: { parameters: [FFI_STRUCTS.Texture, "pointer"], result: "void" },
	// Update GPU texture rectangle with new data
	UpdateTextureRec: { parameters: [FFI_STRUCTS.Texture, FFI_STRUCTS.Rectangle, "pointer"], result: "void" },
	// Generate GPU mipmaps for a texture
	GenTextureMipmaps: { parameters: ["buffer"], result: "void" },
	// Set texture scaling filter mode
	SetTextureFilter: { parameters: [FFI_STRUCTS.Texture, "i32"], result: "void" },
	// Set texture wrapping mode
	SetTextureWrap: { parameters: [FFI_STRUCTS.Texture, "i32"], result: "void" },
	// Draw a Texture2D
	DrawTexture: { parameters: [FFI_STRUCTS.Texture, "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a Texture2D with position defined as Vector2
	DrawTextureV: { parameters: [FFI_STRUCTS.Texture, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a Texture2D with extended parameters
	DrawTextureEx: { parameters: [FFI_STRUCTS.Texture, FFI_STRUCTS.Vector2, "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a part of a texture defined by a rectangle
	DrawTextureRec: { parameters: [FFI_STRUCTS.Texture, FFI_STRUCTS.Rectangle, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a part of a texture defined by a rectangle with 'pro' parameters
	DrawTexturePro: { parameters: [FFI_STRUCTS.Texture, FFI_STRUCTS.Rectangle, FFI_STRUCTS.Rectangle, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draws a texture (or part of it) that stretches or shrinks nicely
	DrawTextureNPatch: { parameters: [FFI_STRUCTS.Texture, FFI_STRUCTS.NPatchInfo, FFI_STRUCTS.Rectangle, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Check if two colors are equal
	ColorIsEqual: { parameters: [FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: "u8" },
	// Get color with alpha applied, alpha goes from 0.0f to 1.0f
	Fade: { parameters: [FFI_STRUCTS.Color, "f32"], result: FFI_STRUCTS.Color },
	// Get hexadecimal value for a Color (0xRRGGBBAA)
	ColorToInt: { parameters: [FFI_STRUCTS.Color], result: "i32" },
	// Get Color normalized as float [0..1]
	ColorNormalize: { parameters: [FFI_STRUCTS.Color], result: FFI_STRUCTS.Vector4 },
	// Get Color from normalized values [0..1]
	ColorFromNormalized: { parameters: [FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Color },
	// Get HSV values for a Color, hue [0..360], saturation/value [0..1]
	ColorToHSV: { parameters: [FFI_STRUCTS.Color], result: FFI_STRUCTS.Vector3 },
	// Get a Color from HSV values, hue [0..360], saturation/value [0..1]
	ColorFromHSV: { parameters: ["f32", "f32", "f32"], result: FFI_STRUCTS.Color },
	// Get color multiplied with another color
	ColorTint: { parameters: [FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: FFI_STRUCTS.Color },
	// Get color with brightness correction, brightness factor goes from -1.0f to 1.0f
	ColorBrightness: { parameters: [FFI_STRUCTS.Color, "f32"], result: FFI_STRUCTS.Color },
	// Get color with contrast correction, contrast values between -1.0f and 1.0f
	ColorContrast: { parameters: [FFI_STRUCTS.Color, "f32"], result: FFI_STRUCTS.Color },
	// Get color with alpha applied, alpha goes from 0.0f to 1.0f
	ColorAlpha: { parameters: [FFI_STRUCTS.Color, "f32"], result: FFI_STRUCTS.Color },
	// Get src alpha-blended into dst color with tint
	ColorAlphaBlend: { parameters: [FFI_STRUCTS.Color, FFI_STRUCTS.Color, FFI_STRUCTS.Color], result: FFI_STRUCTS.Color },
	// Get color lerp interpolation between two colors, factor [0.0f..1.0f]
	ColorLerp: { parameters: [FFI_STRUCTS.Color, FFI_STRUCTS.Color, "f32"], result: FFI_STRUCTS.Color },
	// Get Color structure from hexadecimal value
	GetColor: { parameters: ["u32"], result: FFI_STRUCTS.Color },
	// Get Color from a source pixel pointer of certain format
	GetPixelColor: { parameters: ["pointer", "i32"], result: FFI_STRUCTS.Color },
	// Set color formatted into destination pixel pointer
	SetPixelColor: { parameters: ["pointer", FFI_STRUCTS.Color, "i32"], result: "void" },
	// Get pixel data size in bytes for certain format
	GetPixelDataSize: { parameters: ["i32", "i32", "i32"], result: "i32" },
	// Get the default Font
	GetFontDefault: { parameters: [], result: FFI_STRUCTS.Font },
	// Load font from file into GPU memory (VRAM)
	LoadFont: { parameters: ["buffer"], result: FFI_STRUCTS.Font },
	// Load font from file with extended parameters, use NULL for codepoints and 0 for codepointCount to load the default character set, font size is provided in pixels height
	LoadFontEx: { parameters: ["buffer", "i32", "pointer", "i32"], result: FFI_STRUCTS.Font },
	// Load font from Image (XNA style)
	LoadFontFromImage: { parameters: [FFI_STRUCTS.Image, FFI_STRUCTS.Color, "i32"], result: FFI_STRUCTS.Font },
	// Load font from memory buffer, fileType refers to extension: i.e. '.ttf'
	LoadFontFromMemory: { parameters: ["buffer", "buffer", "i32", "i32", "pointer", "i32"], result: FFI_STRUCTS.Font },
	// Check if a font is valid (font data loaded, WARNING: GPU texture not checked)
	IsFontValid: { parameters: [FFI_STRUCTS.Font], result: "u8" },
	// Load font data for further use
	LoadFontData: { parameters: ["buffer", "i32", "i32", "pointer", "i32", "i32"], result: "buffer" },
	// Generate image font atlas using chars info
	GenImageFontAtlas: { parameters: ["buffer", "pointer", "i32", "i32", "i32", "i32"], result: FFI_STRUCTS.Image },
	// Unload font chars info data (RAM)
	UnloadFontData: { parameters: ["buffer", "i32"], result: "void" },
	// Unload font from GPU memory (VRAM)
	UnloadFont: { parameters: [FFI_STRUCTS.Font], result: "void" },
	// Export font as code file, returns true on success
	ExportFontAsCode: { parameters: [FFI_STRUCTS.Font, "buffer"], result: "u8" },
	// Draw current FPS
	DrawFPS: { parameters: ["i32", "i32"], result: "void" },
	// Draw text (using default font)
	DrawText: { parameters: ["buffer", "i32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw text using font and additional parameters
	DrawTextEx: { parameters: [FFI_STRUCTS.Font, "buffer", FFI_STRUCTS.Vector2, "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw text using Font and pro parameters (rotation)
	DrawTextPro: { parameters: [FFI_STRUCTS.Font, "buffer", FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32", "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw one character (codepoint)
	DrawTextCodepoint: { parameters: [FFI_STRUCTS.Font, "i32", FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw multiple character (codepoint)
	DrawTextCodepoints: { parameters: [FFI_STRUCTS.Font, "pointer", "i32", FFI_STRUCTS.Vector2, "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Set vertical line spacing when drawing with line-breaks
	SetTextLineSpacing: { parameters: ["i32"], result: "void" },
	// Measure string width for default font
	MeasureText: { parameters: ["buffer", "i32"], result: "i32" },
	// Measure string size for Font
	MeasureTextEx: { parameters: [FFI_STRUCTS.Font, "buffer", "f32", "f32"], result: FFI_STRUCTS.Vector2 },
	// Get glyph index position in font for a codepoint (unicode character), fallback to '?' if not found
	GetGlyphIndex: { parameters: [FFI_STRUCTS.Font, "i32"], result: "i32" },
	// Get glyph font info data for a codepoint (unicode character), fallback to '?' if not found
	GetGlyphInfo: { parameters: [FFI_STRUCTS.Font, "i32"], result: FFI_STRUCTS.GlyphInfo },
	// Get glyph rectangle in font atlas for a codepoint (unicode character), fallback to '?' if not found
	GetGlyphAtlasRec: { parameters: [FFI_STRUCTS.Font, "i32"], result: FFI_STRUCTS.Rectangle },
	// Load UTF-8 text encoded from codepoints array
	LoadUTF8: { parameters: ["pointer", "i32"], result: "buffer" },
	// Unload UTF-8 text encoded from codepoints array
	UnloadUTF8: { parameters: ["buffer"], result: "void" },
	// Load all codepoints from a UTF-8 text string, codepoints count returned by parameter
	LoadCodepoints: { parameters: ["buffer", "pointer"], result: "pointer" },
	// Unload codepoints data from memory
	UnloadCodepoints: { parameters: ["pointer"], result: "void" },
	// Get total number of codepoints in a UTF-8 encoded string
	GetCodepointCount: { parameters: ["buffer"], result: "i32" },
	// Get next codepoint in a UTF-8 encoded string, 0x3f('?') is returned on failure
	GetCodepoint: { parameters: ["buffer", "pointer"], result: "i32" },
	// Get next codepoint in a UTF-8 encoded string, 0x3f('?') is returned on failure
	GetCodepointNext: { parameters: ["buffer", "pointer"], result: "i32" },
	// Get previous codepoint in a UTF-8 encoded string, 0x3f('?') is returned on failure
	GetCodepointPrevious: { parameters: ["buffer", "pointer"], result: "i32" },
	// Encode one codepoint into UTF-8 byte array (array length returned as parameter)
	CodepointToUTF8: { parameters: ["i32", "pointer"], result: "buffer" },
	// Copy one string to another, returns bytes copied
	TextCopy: { parameters: ["buffer", "buffer"], result: "i32" },
	// Check if two text string are equal
	TextIsEqual: { parameters: ["buffer", "buffer"], result: "u8" },
	// Get text length, checks for '\0' ending
	TextLength: { parameters: ["buffer"], result: "u32" },
	// Get a piece of a text string
	TextSubtext: { parameters: ["buffer", "i32", "i32"], result: "buffer" },
	// Replace text string (WARNING: memory must be freed!)
	TextReplace: { parameters: ["buffer", "buffer", "buffer"], result: "buffer" },
	// Insert text in a position (WARNING: memory must be freed!)
	TextInsert: { parameters: ["buffer", "buffer", "i32"], result: "buffer" },
	// Join text strings with delimiter
	TextJoin: { parameters: ["buffer", "i32", "buffer"], result: "buffer" },
	// Split text into multiple strings
	TextSplit: { parameters: ["buffer", "i8", "pointer"], result: "buffer" },
	// Append text at specific position and move cursor!
	TextAppend: { parameters: ["buffer", "buffer", "pointer"], result: "void" },
	// Find first text occurrence within a string
	TextFindIndex: { parameters: ["buffer", "buffer"], result: "i32" },
	// Get upper case version of provided string
	TextToUpper: { parameters: ["buffer"], result: "buffer" },
	// Get lower case version of provided string
	TextToLower: { parameters: ["buffer"], result: "buffer" },
	// Get Pascal case notation version of provided string
	TextToPascal: { parameters: ["buffer"], result: "buffer" },
	// Get Snake case notation version of provided string
	TextToSnake: { parameters: ["buffer"], result: "buffer" },
	// Get Camel case notation version of provided string
	TextToCamel: { parameters: ["buffer"], result: "buffer" },
	// Get integer value from text (negative values not supported)
	TextToInteger: { parameters: ["buffer"], result: "i32" },
	// Get float value from text (negative values not supported)
	TextToFloat: { parameters: ["buffer"], result: "f32" },
	// Draw a line in 3D world space
	DrawLine3D: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Color], result: "void" },
	// Draw a point in 3D space, actually a small line
	DrawPoint3D: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Color], result: "void" },
	// Draw a circle in 3D world space
	DrawCircle3D: { parameters: [FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a color-filled triangle (vertex in counter-clockwise order!)
	DrawTriangle3D: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Color], result: "void" },
	// Draw a triangle strip defined by points
	DrawTriangleStrip3D: { parameters: ["buffer", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw cube
	DrawCube: { parameters: [FFI_STRUCTS.Vector3, "f32", "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw cube (Vector version)
	DrawCubeV: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Color], result: "void" },
	// Draw cube wires
	DrawCubeWires: { parameters: [FFI_STRUCTS.Vector3, "f32", "f32", "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw cube wires (Vector version)
	DrawCubeWiresV: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Color], result: "void" },
	// Draw sphere
	DrawSphere: { parameters: [FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw sphere with extended parameters
	DrawSphereEx: { parameters: [FFI_STRUCTS.Vector3, "f32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw sphere wires
	DrawSphereWires: { parameters: [FFI_STRUCTS.Vector3, "f32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a cylinder/cone
	DrawCylinder: { parameters: [FFI_STRUCTS.Vector3, "f32", "f32", "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a cylinder with base at startPos and top at endPos
	DrawCylinderEx: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32", "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a cylinder/cone wires
	DrawCylinderWires: { parameters: [FFI_STRUCTS.Vector3, "f32", "f32", "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a cylinder wires with base at startPos and top at endPos
	DrawCylinderWiresEx: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32", "f32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a capsule with the center of its sphere caps at startPos and endPos
	DrawCapsule: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw capsule wireframe with the center of its sphere caps at startPos and endPos
	DrawCapsuleWires: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32", "i32", "i32", FFI_STRUCTS.Color], result: "void" },
	// Draw a plane XZ
	DrawPlane: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a ray line
	DrawRay: { parameters: [FFI_STRUCTS.Ray, FFI_STRUCTS.Color], result: "void" },
	// Draw a grid (centered at (0, 0, 0))
	DrawGrid: { parameters: ["i32", "f32"], result: "void" },
	// Load model from files (meshes and materials)
	LoadModel: { parameters: ["buffer"], result: FFI_STRUCTS.Model },
	// Load model from generated mesh (default material)
	LoadModelFromMesh: { parameters: [FFI_STRUCTS.Mesh], result: FFI_STRUCTS.Model },
	// Check if a model is valid (loaded in GPU, VAO/VBOs)
	IsModelValid: { parameters: [FFI_STRUCTS.Model], result: "u8" },
	// Unload model (including meshes) from memory (RAM and/or VRAM)
	UnloadModel: { parameters: [FFI_STRUCTS.Model], result: "void" },
	// Compute model bounding box limits (considers all meshes)
	GetModelBoundingBox: { parameters: [FFI_STRUCTS.Model], result: FFI_STRUCTS.BoundingBox },
	// Draw a model (with texture if set)
	DrawModel: { parameters: [FFI_STRUCTS.Model, FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a model with extended parameters
	DrawModelEx: { parameters: [FFI_STRUCTS.Model, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Vector3, FFI_STRUCTS.Color], result: "void" },
	// Draw a model wires (with texture if set)
	DrawModelWires: { parameters: [FFI_STRUCTS.Model, FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a model wires (with texture if set) with extended parameters
	DrawModelWiresEx: { parameters: [FFI_STRUCTS.Model, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Vector3, FFI_STRUCTS.Color], result: "void" },
	// Draw a model as points
	DrawModelPoints: { parameters: [FFI_STRUCTS.Model, FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a model as points with extended parameters
	DrawModelPointsEx: { parameters: [FFI_STRUCTS.Model, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Vector3, FFI_STRUCTS.Color], result: "void" },
	// [rlgl] Disable backface culling (draw inside of cube)
	rlDisableBackfaceCulling: { parameters: [], result: "void" },
	// [rlgl] Enable backface culling
	rlEnableBackfaceCulling: { parameters: [], result: "void" },
	// [rlgl] Disable depth mask (depth writes)
	rlDisableDepthMask: { parameters: [], result: "void" },
	// [rlgl] Enable depth mask (depth writes)
	rlEnableDepthMask: { parameters: [], result: "void" },
	// Draw bounding box (wires)
	DrawBoundingBox: { parameters: [FFI_STRUCTS.BoundingBox, FFI_STRUCTS.Color], result: "void" },
	// Draw a billboard texture
	DrawBillboard: { parameters: [FFI_STRUCTS.Camera3D, FFI_STRUCTS.Texture, FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Color], result: "void" },
	// Draw a billboard texture defined by source
	DrawBillboardRec: { parameters: [FFI_STRUCTS.Camera3D, FFI_STRUCTS.Texture, FFI_STRUCTS.Rectangle, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector2, FFI_STRUCTS.Color], result: "void" },
	// Draw a billboard texture defined by source and rotation
	DrawBillboardPro: { parameters: [FFI_STRUCTS.Camera3D, FFI_STRUCTS.Texture, FFI_STRUCTS.Rectangle, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32", FFI_STRUCTS.Color], result: "void" },
	// Upload mesh vertex data in GPU and provide VAO/VBO ids
	UploadMesh: { parameters: ["buffer", "u8"], result: "void" },
	// Update mesh vertex data in GPU for a specific buffer index
	UpdateMeshBuffer: { parameters: [FFI_STRUCTS.Mesh, "i32", "pointer", "i32", "i32"], result: "void" },
	// Unload mesh data from CPU and GPU
	UnloadMesh: { parameters: [FFI_STRUCTS.Mesh], result: "void" },
	// Draw a 3d mesh with material and transform
	DrawMesh: { parameters: [FFI_STRUCTS.Mesh, FFI_STRUCTS.Material, FFI_STRUCTS.Matrix], result: "void" },
	// Draw multiple mesh instances with material and different transforms
	DrawMeshInstanced: { parameters: [FFI_STRUCTS.Mesh, FFI_STRUCTS.Material, "buffer", "i32"], result: "void" },
	// Compute mesh bounding box limits
	GetMeshBoundingBox: { parameters: [FFI_STRUCTS.Mesh], result: FFI_STRUCTS.BoundingBox },
	// Compute mesh tangents
	GenMeshTangents: { parameters: ["buffer"], result: "void" },
	// Export mesh data to file, returns true on success
	ExportMesh: { parameters: [FFI_STRUCTS.Mesh, "buffer"], result: "u8" },
	// Export mesh as code file (.h) defining multiple arrays of vertex attributes
	ExportMeshAsCode: { parameters: [FFI_STRUCTS.Mesh, "buffer"], result: "u8" },
	// Generate polygonal mesh
	GenMeshPoly: { parameters: ["i32", "f32"], result: FFI_STRUCTS.Mesh },
	// Generate plane mesh (with subdivisions)
	GenMeshPlane: { parameters: ["f32", "f32", "i32", "i32"], result: FFI_STRUCTS.Mesh },
	// Generate cuboid mesh
	GenMeshCube: { parameters: ["f32", "f32", "f32"], result: FFI_STRUCTS.Mesh },
	// Generate sphere mesh (standard sphere)
	GenMeshSphere: { parameters: ["f32", "i32", "i32"], result: FFI_STRUCTS.Mesh },
	// Generate half-sphere mesh (no bottom cap)
	GenMeshHemiSphere: { parameters: ["f32", "i32", "i32"], result: FFI_STRUCTS.Mesh },
	// Generate cylinder mesh
	GenMeshCylinder: { parameters: ["f32", "f32", "i32"], result: FFI_STRUCTS.Mesh },
	// Generate cone/pyramid mesh
	GenMeshCone: { parameters: ["f32", "f32", "i32"], result: FFI_STRUCTS.Mesh },
	// Generate torus mesh
	GenMeshTorus: { parameters: ["f32", "f32", "i32", "i32"], result: FFI_STRUCTS.Mesh },
	// Generate trefoil knot mesh
	GenMeshKnot: { parameters: ["f32", "f32", "i32", "i32"], result: FFI_STRUCTS.Mesh },
	// Generate heightmap mesh from image data
	GenMeshHeightmap: { parameters: [FFI_STRUCTS.Image, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Mesh },
	// Generate cubes-based map mesh from image data
	GenMeshCubicmap: { parameters: [FFI_STRUCTS.Image, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Mesh },
	// Load materials from model file
	LoadMaterials: { parameters: ["buffer", "pointer"], result: "buffer" },
	// Load default material (Supports: DIFFUSE, SPECULAR, NORMAL maps)
	LoadMaterialDefault: { parameters: [], result: FFI_STRUCTS.Material },
	// Check if a material is valid (shader assigned, map textures loaded in GPU)
	IsMaterialValid: { parameters: [FFI_STRUCTS.Material], result: "u8" },
	// Unload material from GPU memory (VRAM)
	UnloadMaterial: { parameters: [FFI_STRUCTS.Material], result: "void" },
	// Set texture for a material map type (MATERIAL_MAP_DIFFUSE, MATERIAL_MAP_SPECULAR...)
	SetMaterialTexture: { parameters: ["buffer", "i32", FFI_STRUCTS.Texture], result: "void" },
	// Set material for a mesh
	SetModelMeshMaterial: { parameters: ["buffer", "i32", "i32"], result: "void" },
	// Load model animations from file
	LoadModelAnimations: { parameters: ["buffer", "pointer"], result: "buffer" },
	// Update model animation pose (CPU)
	UpdateModelAnimation: { parameters: [FFI_STRUCTS.Model, FFI_STRUCTS.ModelAnimation, "i32"], result: "void" },
	// Update model animation mesh bone matrices (GPU skinning)
	UpdateModelAnimationBones: { parameters: [FFI_STRUCTS.Model, FFI_STRUCTS.ModelAnimation, "i32"], result: "void" },
	// Unload animation data
	UnloadModelAnimation: { parameters: [FFI_STRUCTS.ModelAnimation], result: "void" },
	// Unload animation array data
	UnloadModelAnimations: { parameters: ["buffer", "i32"], result: "void" },
	// Check model animation skeleton match
	IsModelAnimationValid: { parameters: [FFI_STRUCTS.Model, FFI_STRUCTS.ModelAnimation], result: "u8" },
	// Check collision between two spheres
	CheckCollisionSpheres: { parameters: [FFI_STRUCTS.Vector3, "f32", FFI_STRUCTS.Vector3, "f32"], result: "u8" },
	// Check collision between two bounding boxes
	CheckCollisionBoxes: { parameters: [FFI_STRUCTS.BoundingBox, FFI_STRUCTS.BoundingBox], result: "u8" },
	// Check collision between box and sphere
	CheckCollisionBoxSphere: { parameters: [FFI_STRUCTS.BoundingBox, FFI_STRUCTS.Vector3, "f32"], result: "u8" },
	// Get collision info between ray and sphere
	GetRayCollisionSphere: { parameters: [FFI_STRUCTS.Ray, FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.RayCollision },
	// Get collision info between ray and box
	GetRayCollisionBox: { parameters: [FFI_STRUCTS.Ray, FFI_STRUCTS.BoundingBox], result: FFI_STRUCTS.RayCollision },
	// Get collision info between ray and mesh
	GetRayCollisionMesh: { parameters: [FFI_STRUCTS.Ray, FFI_STRUCTS.Mesh, FFI_STRUCTS.Matrix], result: FFI_STRUCTS.RayCollision },
	// Get collision info between ray and triangle
	GetRayCollisionTriangle: { parameters: [FFI_STRUCTS.Ray, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.RayCollision },
	// Get collision info between ray and quad
	GetRayCollisionQuad: { parameters: [FFI_STRUCTS.Ray, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.RayCollision },
	// Initialize audio device and context
	InitAudioDevice: { parameters: [], result: "void" },
	// Close the audio device and context
	CloseAudioDevice: { parameters: [], result: "void" },
	// Check if audio device has been initialized successfully
	IsAudioDeviceReady: { parameters: [], result: "u8" },
	// Set master volume (listener)
	SetMasterVolume: { parameters: ["f32"], result: "void" },
	// Get master volume (listener)
	GetMasterVolume: { parameters: [], result: "f32" },
	// Load wave data from file
	LoadWave: { parameters: ["buffer"], result: FFI_STRUCTS.Wave },
	// Load wave from memory buffer, fileType refers to extension: i.e. '.wav'
	LoadWaveFromMemory: { parameters: ["buffer", "buffer", "i32"], result: FFI_STRUCTS.Wave },
	// Checks if wave data is valid (data loaded and parameters)
	IsWaveValid: { parameters: [FFI_STRUCTS.Wave], result: "u8" },
	// Load sound from file
	LoadSound: { parameters: ["buffer"], result: FFI_STRUCTS.Sound },
	// Load sound from wave data
	LoadSoundFromWave: { parameters: [FFI_STRUCTS.Wave], result: FFI_STRUCTS.Sound },
	// Create a new sound that shares the same sample data as the source sound, does not own the sound data
	LoadSoundAlias: { parameters: [FFI_STRUCTS.Sound], result: FFI_STRUCTS.Sound },
	// Checks if a sound is valid (data loaded and buffers initialized)
	IsSoundValid: { parameters: [FFI_STRUCTS.Sound], result: "u8" },
	// Update sound buffer with new data
	UpdateSound: { parameters: [FFI_STRUCTS.Sound, "pointer", "i32"], result: "void" },
	// Unload wave data
	UnloadWave: { parameters: [FFI_STRUCTS.Wave], result: "void" },
	// Unload sound
	UnloadSound: { parameters: [FFI_STRUCTS.Sound], result: "void" },
	// Unload a sound alias (does not deallocate sample data)
	UnloadSoundAlias: { parameters: [FFI_STRUCTS.Sound], result: "void" },
	// Export wave data to file, returns true on success
	ExportWave: { parameters: [FFI_STRUCTS.Wave, "buffer"], result: "u8" },
	// Export wave sample data to code (.h), returns true on success
	ExportWaveAsCode: { parameters: [FFI_STRUCTS.Wave, "buffer"], result: "u8" },
	// Play a sound
	PlaySound: { parameters: [FFI_STRUCTS.Sound], result: "void" },
	// Stop playing a sound
	StopSound: { parameters: [FFI_STRUCTS.Sound], result: "void" },
	// Pause a sound
	PauseSound: { parameters: [FFI_STRUCTS.Sound], result: "void" },
	// Resume a paused sound
	ResumeSound: { parameters: [FFI_STRUCTS.Sound], result: "void" },
	// Check if a sound is currently playing
	IsSoundPlaying: { parameters: [FFI_STRUCTS.Sound], result: "u8" },
	// Set volume for a sound (1.0 is max level)
	SetSoundVolume: { parameters: [FFI_STRUCTS.Sound, "f32"], result: "void" },
	// Set pitch for a sound (1.0 is base level)
	SetSoundPitch: { parameters: [FFI_STRUCTS.Sound, "f32"], result: "void" },
	// Set pan for a sound (0.5 is center)
	SetSoundPan: { parameters: [FFI_STRUCTS.Sound, "f32"], result: "void" },
	// Copy a wave to a new wave
	WaveCopy: { parameters: [FFI_STRUCTS.Wave], result: FFI_STRUCTS.Wave },
	// Crop a wave to defined frames range
	WaveCrop: { parameters: ["buffer", "i32", "i32"], result: "void" },
	// Convert wave data to desired format
	WaveFormat: { parameters: ["buffer", "i32", "i32", "i32"], result: "void" },
	// Load samples data from wave as a 32bit float data array
	LoadWaveSamples: { parameters: [FFI_STRUCTS.Wave], result: "pointer" },
	// Unload samples data loaded with LoadWaveSamples()
	UnloadWaveSamples: { parameters: ["pointer"], result: "void" },
	// Load music stream from file
	LoadMusicStream: { parameters: ["buffer"], result: FFI_STRUCTS.Music },
	// Load music stream from data
	LoadMusicStreamFromMemory: { parameters: ["buffer", "buffer", "i32"], result: FFI_STRUCTS.Music },
	// Checks if a music stream is valid (context and buffers initialized)
	IsMusicValid: { parameters: [FFI_STRUCTS.Music], result: "u8" },
	// Unload music stream
	UnloadMusicStream: { parameters: [FFI_STRUCTS.Music], result: "void" },
	// Start music playing
	PlayMusicStream: { parameters: [FFI_STRUCTS.Music], result: "void" },
	// Check if music is playing
	IsMusicStreamPlaying: { parameters: [FFI_STRUCTS.Music], result: "u8" },
	// Updates buffers for music streaming
	UpdateMusicStream: { parameters: [FFI_STRUCTS.Music], result: "void" },
	// Stop music playing
	StopMusicStream: { parameters: [FFI_STRUCTS.Music], result: "void" },
	// Pause music playing
	PauseMusicStream: { parameters: [FFI_STRUCTS.Music], result: "void" },
	// Resume playing paused music
	ResumeMusicStream: { parameters: [FFI_STRUCTS.Music], result: "void" },
	// Seek music to a position (in seconds)
	SeekMusicStream: { parameters: [FFI_STRUCTS.Music, "f32"], result: "void" },
	// Set volume for music (1.0 is max level)
	SetMusicVolume: { parameters: [FFI_STRUCTS.Music, "f32"], result: "void" },
	// Set pitch for a music (1.0 is base level)
	SetMusicPitch: { parameters: [FFI_STRUCTS.Music, "f32"], result: "void" },
	// Set pan for a music (0.5 is center)
	SetMusicPan: { parameters: [FFI_STRUCTS.Music, "f32"], result: "void" },
	// Get music time length (in seconds)
	GetMusicTimeLength: { parameters: [FFI_STRUCTS.Music], result: "f32" },
	// Get current music time played (in seconds)
	GetMusicTimePlayed: { parameters: [FFI_STRUCTS.Music], result: "f32" },
	// Load audio stream (to stream raw audio pcm data)
	LoadAudioStream: { parameters: ["u32", "u32", "u32"], result: FFI_STRUCTS.AudioStream },
	// Checks if an audio stream is valid (buffers initialized)
	IsAudioStreamValid: { parameters: [FFI_STRUCTS.AudioStream], result: "u8" },
	// Unload audio stream and free memory
	UnloadAudioStream: { parameters: [FFI_STRUCTS.AudioStream], result: "void" },
	// Update audio stream buffers with data
	UpdateAudioStream: { parameters: [FFI_STRUCTS.AudioStream, "pointer", "i32"], result: "void" },
	// Check if any audio stream buffers requires refill
	IsAudioStreamProcessed: { parameters: [FFI_STRUCTS.AudioStream], result: "u8" },
	// Play audio stream
	PlayAudioStream: { parameters: [FFI_STRUCTS.AudioStream], result: "void" },
	// Pause audio stream
	PauseAudioStream: { parameters: [FFI_STRUCTS.AudioStream], result: "void" },
	// Resume audio stream
	ResumeAudioStream: { parameters: [FFI_STRUCTS.AudioStream], result: "void" },
	// Check if audio stream is playing
	IsAudioStreamPlaying: { parameters: [FFI_STRUCTS.AudioStream], result: "u8" },
	// Stop audio stream
	StopAudioStream: { parameters: [FFI_STRUCTS.AudioStream], result: "void" },
	// Set volume for audio stream (1.0 is max level)
	SetAudioStreamVolume: { parameters: [FFI_STRUCTS.AudioStream, "f32"], result: "void" },
	// Set pitch for audio stream (1.0 is base level)
	SetAudioStreamPitch: { parameters: [FFI_STRUCTS.AudioStream, "f32"], result: "void" },
	// Set pan for audio stream (0.5 is centered)
	SetAudioStreamPan: { parameters: [FFI_STRUCTS.AudioStream, "f32"], result: "void" },
	// Default size for new audio streams
	SetAudioStreamBufferSizeDefault: { parameters: ["i32"], result: "void" },
	// Audio thread callback to request new data
	SetAudioStreamCallback: { parameters: [FFI_STRUCTS.AudioStream, "function"], result: "void" },
	// Attach audio stream processor to stream, receives the samples as 'float'
	AttachAudioStreamProcessor: { parameters: [FFI_STRUCTS.AudioStream, "function"], result: "void" },
	// Detach audio stream processor from stream
	DetachAudioStreamProcessor: { parameters: [FFI_STRUCTS.AudioStream, "function"], result: "void" },
	// Attach audio stream processor to the entire audio pipeline, receives the samples as 'float'
	AttachAudioMixedProcessor: { parameters: ["function"], result: "void" },
	// Detach audio stream processor from the entire audio pipeline
	DetachAudioMixedProcessor: { parameters: ["function"], result: "void" },
	// RL MATH API
	Clamp: { parameters: ["f32", "f32", "f32"], result: "f32" },
	Lerp: { parameters: ["f32", "f32", "f32"], result: "f32" },
	Normalize: { parameters: ["f32", "f32", "f32"], result: "f32" },
	Remap: { parameters: ["f32", "f32", "f32", "f32", "f32"], result: "f32" },
	Wrap: { parameters: ["f32", "f32", "f32"], result: "f32" },
	FloatEquals: { parameters: ["f32", "f32"], result: "i32" },
	Vector2Zero: { parameters: [], result: FFI_STRUCTS.Vector2 },
	Vector2One: { parameters: [], result: FFI_STRUCTS.Vector2 },
	Vector2Add: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2AddValue: { parameters: [FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	Vector2Subtract: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2SubtractValue: { parameters: [FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	Vector2Length: { parameters: [FFI_STRUCTS.Vector2], result: "f32" },
	Vector2LengthSqr: { parameters: [FFI_STRUCTS.Vector2], result: "f32" },
	Vector2DotProduct: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: "f32" },
	Vector2Distance: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: "f32" },
	Vector2DistanceSqr: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: "f32" },
	Vector2Angle: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: "f32" },
	Vector2LineAngle: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: "f32" },
	Vector2Scale: { parameters: [FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	Vector2Multiply: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2Negate: { parameters: [FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2Divide: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2Normalize: { parameters: [FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2Transform: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Vector2 },
	Vector2Lerp: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	Vector2Reflect: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2Min: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2Max: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2Rotate: { parameters: [FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	Vector2MoveTowards: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	Vector2Invert: { parameters: [FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2Clamp: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: FFI_STRUCTS.Vector2 },
	Vector2ClampValue: { parameters: [FFI_STRUCTS.Vector2, "f32", "f32"], result: FFI_STRUCTS.Vector2 },
	Vector2Equals: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2], result: "i32" },
	Vector2Refract: { parameters: [FFI_STRUCTS.Vector2, FFI_STRUCTS.Vector2, "f32"], result: FFI_STRUCTS.Vector2 },
	Vector3Zero: { parameters: [], result: FFI_STRUCTS.Vector3 },
	Vector3One: { parameters: [], result: FFI_STRUCTS.Vector3 },
	Vector3Add: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3AddValue: { parameters: [FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Vector3 },
	Vector3Subtract: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3SubtractValue: { parameters: [FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Vector3 },
	Vector3Scale: { parameters: [FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Vector3 },
	Vector3Multiply: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3CrossProduct: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Perpendicular: { parameters: [FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Length: { parameters: [FFI_STRUCTS.Vector3], result: "f32" },
	Vector3LengthSqr: { parameters: [FFI_STRUCTS.Vector3], result: "f32" },
	Vector3DotProduct: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: "f32" },
	Vector3Distance: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: "f32" },
	Vector3DistanceSqr: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: "f32" },
	Vector3Angle: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: "f32" },
	Vector3Negate: { parameters: [FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Divide: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Normalize: { parameters: [FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Project: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Reject: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3OrthoNormalize: { parameters: ["pointer", "pointer"], result: "void" },
	Vector3Transform: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Vector3 },
	Vector3RotateByQuaternion: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector3 },
	Vector3RotateByAxisAngle: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Vector3 },
	Vector3MoveTowards: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Vector3 },
	Vector3Lerp: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Vector3 },
	Vector3CubicHermite: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Vector3 },
	Vector3Reflect: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Min: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Max: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Barycenter: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Unproject: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Matrix, FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Vector3 },
	Vector3ToFloatV: { parameters: [FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Invert: { parameters: [FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3Clamp: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector3 },
	Vector3ClampValue: { parameters: [FFI_STRUCTS.Vector3, "f32", "f32"], result: FFI_STRUCTS.Vector3 },
	Vector3Equals: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: "i32" },
	Vector3Refract: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Vector3 },
	Vector4Zero: { parameters: [], result: FFI_STRUCTS.Vector4 },
	Vector4One: { parameters: [], result: FFI_STRUCTS.Vector4 },
	Vector4Add: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	Vector4AddValue: { parameters: [FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	Vector4Subtract: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	Vector4SubtractValue: { parameters: [FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	Vector4Length: { parameters: [FFI_STRUCTS.Vector4], result: "f32" },
	Vector4LengthSqr: { parameters: [FFI_STRUCTS.Vector4], result: "f32" },
	Vector4DotProduct: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: "f32" },
	Vector4Distance: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: "f32" },
	Vector4DistanceSqr: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: "f32" },
	Vector4Scale: { parameters: [FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	Vector4Multiply: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	Vector4Negate: { parameters: [FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	Vector4Divide: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	Vector4Normalize: { parameters: [FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	Vector4Min: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	Vector4Max: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	Vector4Lerp: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	Vector4MoveTowards: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	Vector4Invert: { parameters: [FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	Vector4Equals: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: "i32" },
	MatrixDeterminant: { parameters: [FFI_STRUCTS.Matrix], result: "f32" },
	MatrixTrace: { parameters: [FFI_STRUCTS.Matrix], result: "f32" },
	MatrixTranspose: { parameters: [FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Matrix },
	MatrixInvert: { parameters: [FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Matrix },
	MatrixIdentity: { parameters: [], result: FFI_STRUCTS.Matrix },
	MatrixAdd: { parameters: [FFI_STRUCTS.Matrix, FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Matrix },
	MatrixSubtract: { parameters: [FFI_STRUCTS.Matrix, FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Matrix },
	MatrixMultiply: { parameters: [FFI_STRUCTS.Matrix, FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Matrix },
	MatrixTranslate: { parameters: ["f32", "f32", "f32"], result: FFI_STRUCTS.Matrix },
	MatrixRotate: { parameters: [FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Matrix },
	MatrixRotateX: { parameters: ["f32"], result: FFI_STRUCTS.Matrix },
	MatrixRotateY: { parameters: ["f32"], result: FFI_STRUCTS.Matrix },
	MatrixRotateZ: { parameters: ["f32"], result: FFI_STRUCTS.Matrix },
	MatrixRotateXYZ: { parameters: [FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Matrix },
	MatrixRotateZYX: { parameters: [FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Matrix },
	MatrixScale: { parameters: ["f32", "f32", "f32"], result: FFI_STRUCTS.Matrix },
	MatrixFrustum: { parameters: ["f64", "f64", "f64", "f64", "f64", "f64"], result: FFI_STRUCTS.Matrix },
	MatrixPerspective: { parameters: ["f64", "f64", "f64", "f64"], result: FFI_STRUCTS.Matrix },
	MatrixOrtho: { parameters: ["f64", "f64", "f64", "f64", "f64", "f64"], result: FFI_STRUCTS.Matrix },
	MatrixLookAt: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Matrix },
	MatrixToFloatV: { parameters: [FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Matrix },
	QuaternionAdd: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	QuaternionAddValue: { parameters: [FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	QuaternionSubtract: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	QuaternionSubtractValue: { parameters: [FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	QuaternionIdentity: { parameters: [], result: FFI_STRUCTS.Vector4 },
	QuaternionLength: { parameters: [FFI_STRUCTS.Vector4], result: "f32" },
	QuaternionNormalize: { parameters: [FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	QuaternionInvert: { parameters: [FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	QuaternionMultiply: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	QuaternionScale: { parameters: [FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	QuaternionDivide: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector4 },
	QuaternionLerp: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	QuaternionNlerp: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	QuaternionSlerp: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	QuaternionCubicHermiteSpline: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4, "f32"], result: FFI_STRUCTS.Vector4 },
	QuaternionFromVector3ToVector3: { parameters: [FFI_STRUCTS.Vector3, FFI_STRUCTS.Vector3], result: FFI_STRUCTS.Vector4 },
	QuaternionFromMatrix: { parameters: [FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Vector4 },
	QuaternionToMatrix: { parameters: [FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Matrix },
	QuaternionFromAxisAngle: { parameters: [FFI_STRUCTS.Vector3, "f32"], result: FFI_STRUCTS.Vector4 },
	QuaternionToAxisAngle: { parameters: [FFI_STRUCTS.Vector4, "pointer", "pointer"], result: "void" },
	QuaternionFromEuler: { parameters: ["f32", "f32", "f32"], result: FFI_STRUCTS.Vector4 },
	QuaternionToEuler: { parameters: [FFI_STRUCTS.Vector4], result: FFI_STRUCTS.Vector3 },
	QuaternionTransform: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Matrix], result: FFI_STRUCTS.Vector4 },
	QuaternionEquals: { parameters: [FFI_STRUCTS.Vector4, FFI_STRUCTS.Vector4], result: "i32" },
	MatrixDecompose: { parameters: [FFI_STRUCTS.Matrix, "pointer", "pointer", "pointer"], result: "void" },
  },
);

// Write the result to the bindings file
