// This file is generated by generate_structs.ts
// deno-lint-ignore-file no-explicit-any

export const littleEndian = (() => {
  const buffer = new ArrayBuffer(2);
  new DataView(buffer).setInt16(0, 256, true);
  return new Int16Array(buffer)[0] === 256;
})();

const _POINTER_SIZE = 8;

export class Vector2 {
  static readonly SIZE = 8;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(options: Partial<{ x: number; y: number }>);
  constructor(x: number, y: number);
  constructor(
    arg0: Uint8Array<ArrayBuffer> | Partial<{ x: number; y: number }> | number,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Vector2.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).x !== undefined) this.x = (arg0 as any).x;
      if ((arg0 as any).y !== undefined) this.y = (arg0 as any).y;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.x = args[0] as any;
    if (args[1] !== undefined) this.y = args[1] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Vector2 {
    return new Vector2(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Vector2.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get x(): number {
    return this.#view.getFloat32(0, littleEndian) as number;
  }

  set x(value: number) {
    this.#view.setFloat32(0, value as any, littleEndian);
  }

  get y(): number {
    return this.#view.getFloat32(4, littleEndian) as number;
  }

  set y(value: number) {
    this.#view.setFloat32(4, value as any, littleEndian);
  }
}

export class Vector3 {
  static readonly SIZE = 12;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(options: Partial<{ x: number; y: number; z: number }>);
  constructor(x: number, y: number, z: number);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ x: number; y: number; z: number }>
      | number,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Vector3.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).x !== undefined) this.x = (arg0 as any).x;
      if ((arg0 as any).y !== undefined) this.y = (arg0 as any).y;
      if ((arg0 as any).z !== undefined) this.z = (arg0 as any).z;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.x = args[0] as any;
    if (args[1] !== undefined) this.y = args[1] as any;
    if (args[2] !== undefined) this.z = args[2] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Vector3 {
    return new Vector3(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Vector3.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get x(): number {
    return this.#view.getFloat32(0, littleEndian) as number;
  }

  set x(value: number) {
    this.#view.setFloat32(0, value as any, littleEndian);
  }

  get y(): number {
    return this.#view.getFloat32(4, littleEndian) as number;
  }

  set y(value: number) {
    this.#view.setFloat32(4, value as any, littleEndian);
  }

  get z(): number {
    return this.#view.getFloat32(8, littleEndian) as number;
  }

  set z(value: number) {
    this.#view.setFloat32(8, value as any, littleEndian);
  }
}

export class Vector4 {
  static readonly SIZE = 16;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(options: Partial<{ x: number; y: number; z: number; w: number }>);
  constructor(x: number, y: number, z: number, w: number);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ x: number; y: number; z: number; w: number }>
      | number,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Vector4.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).x !== undefined) this.x = (arg0 as any).x;
      if ((arg0 as any).y !== undefined) this.y = (arg0 as any).y;
      if ((arg0 as any).z !== undefined) this.z = (arg0 as any).z;
      if ((arg0 as any).w !== undefined) this.w = (arg0 as any).w;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.x = args[0] as any;
    if (args[1] !== undefined) this.y = args[1] as any;
    if (args[2] !== undefined) this.z = args[2] as any;
    if (args[3] !== undefined) this.w = args[3] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Vector4 {
    return new Vector4(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Vector4.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get x(): number {
    return this.#view.getFloat32(0, littleEndian) as number;
  }

  set x(value: number) {
    this.#view.setFloat32(0, value as any, littleEndian);
  }

  get y(): number {
    return this.#view.getFloat32(4, littleEndian) as number;
  }

  set y(value: number) {
    this.#view.setFloat32(4, value as any, littleEndian);
  }

  get z(): number {
    return this.#view.getFloat32(8, littleEndian) as number;
  }

  set z(value: number) {
    this.#view.setFloat32(8, value as any, littleEndian);
  }

  get w(): number {
    return this.#view.getFloat32(12, littleEndian) as number;
  }

  set w(value: number) {
    this.#view.setFloat32(12, value as any, littleEndian);
  }
}

export class Matrix {
  static readonly SIZE = 64;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<
      {
        m0: number;
        m4: number;
        m8: number;
        m12: number;
        m1: number;
        m5: number;
        m9: number;
        m13: number;
        m2: number;
        m6: number;
        m10: number;
        m14: number;
        m3: number;
        m7: number;
        m11: number;
        m15: number;
      }
    >,
  );
  constructor(
    m0: number,
    m4: number,
    m8: number,
    m12: number,
    m1: number,
    m5: number,
    m9: number,
    m13: number,
    m2: number,
    m6: number,
    m10: number,
    m14: number,
    m3: number,
    m7: number,
    m11: number,
    m15: number,
  );
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<
        {
          m0: number;
          m4: number;
          m8: number;
          m12: number;
          m1: number;
          m5: number;
          m9: number;
          m13: number;
          m2: number;
          m6: number;
          m10: number;
          m14: number;
          m3: number;
          m7: number;
          m11: number;
          m15: number;
        }
      >
      | number,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Matrix.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).m0 !== undefined) this.m0 = (arg0 as any).m0;
      if ((arg0 as any).m4 !== undefined) this.m4 = (arg0 as any).m4;
      if ((arg0 as any).m8 !== undefined) this.m8 = (arg0 as any).m8;
      if ((arg0 as any).m12 !== undefined) this.m12 = (arg0 as any).m12;
      if ((arg0 as any).m1 !== undefined) this.m1 = (arg0 as any).m1;
      if ((arg0 as any).m5 !== undefined) this.m5 = (arg0 as any).m5;
      if ((arg0 as any).m9 !== undefined) this.m9 = (arg0 as any).m9;
      if ((arg0 as any).m13 !== undefined) this.m13 = (arg0 as any).m13;
      if ((arg0 as any).m2 !== undefined) this.m2 = (arg0 as any).m2;
      if ((arg0 as any).m6 !== undefined) this.m6 = (arg0 as any).m6;
      if ((arg0 as any).m10 !== undefined) this.m10 = (arg0 as any).m10;
      if ((arg0 as any).m14 !== undefined) this.m14 = (arg0 as any).m14;
      if ((arg0 as any).m3 !== undefined) this.m3 = (arg0 as any).m3;
      if ((arg0 as any).m7 !== undefined) this.m7 = (arg0 as any).m7;
      if ((arg0 as any).m11 !== undefined) this.m11 = (arg0 as any).m11;
      if ((arg0 as any).m15 !== undefined) this.m15 = (arg0 as any).m15;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.m0 = args[0] as any;
    if (args[1] !== undefined) this.m4 = args[1] as any;
    if (args[2] !== undefined) this.m8 = args[2] as any;
    if (args[3] !== undefined) this.m12 = args[3] as any;
    if (args[4] !== undefined) this.m1 = args[4] as any;
    if (args[5] !== undefined) this.m5 = args[5] as any;
    if (args[6] !== undefined) this.m9 = args[6] as any;
    if (args[7] !== undefined) this.m13 = args[7] as any;
    if (args[8] !== undefined) this.m2 = args[8] as any;
    if (args[9] !== undefined) this.m6 = args[9] as any;
    if (args[10] !== undefined) this.m10 = args[10] as any;
    if (args[11] !== undefined) this.m14 = args[11] as any;
    if (args[12] !== undefined) this.m3 = args[12] as any;
    if (args[13] !== undefined) this.m7 = args[13] as any;
    if (args[14] !== undefined) this.m11 = args[14] as any;
    if (args[15] !== undefined) this.m15 = args[15] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Matrix {
    return new Matrix(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Matrix.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get m0(): number {
    return this.#view.getFloat32(0, littleEndian) as number;
  }

  set m0(value: number) {
    this.#view.setFloat32(0, value as any, littleEndian);
  }

  get m4(): number {
    return this.#view.getFloat32(4, littleEndian) as number;
  }

  set m4(value: number) {
    this.#view.setFloat32(4, value as any, littleEndian);
  }

  get m8(): number {
    return this.#view.getFloat32(8, littleEndian) as number;
  }

  set m8(value: number) {
    this.#view.setFloat32(8, value as any, littleEndian);
  }

  get m12(): number {
    return this.#view.getFloat32(12, littleEndian) as number;
  }

  set m12(value: number) {
    this.#view.setFloat32(12, value as any, littleEndian);
  }

  get m1(): number {
    return this.#view.getFloat32(16, littleEndian) as number;
  }

  set m1(value: number) {
    this.#view.setFloat32(16, value as any, littleEndian);
  }

  get m5(): number {
    return this.#view.getFloat32(20, littleEndian) as number;
  }

  set m5(value: number) {
    this.#view.setFloat32(20, value as any, littleEndian);
  }

  get m9(): number {
    return this.#view.getFloat32(24, littleEndian) as number;
  }

  set m9(value: number) {
    this.#view.setFloat32(24, value as any, littleEndian);
  }

  get m13(): number {
    return this.#view.getFloat32(28, littleEndian) as number;
  }

  set m13(value: number) {
    this.#view.setFloat32(28, value as any, littleEndian);
  }

  get m2(): number {
    return this.#view.getFloat32(32, littleEndian) as number;
  }

  set m2(value: number) {
    this.#view.setFloat32(32, value as any, littleEndian);
  }

  get m6(): number {
    return this.#view.getFloat32(36, littleEndian) as number;
  }

  set m6(value: number) {
    this.#view.setFloat32(36, value as any, littleEndian);
  }

  get m10(): number {
    return this.#view.getFloat32(40, littleEndian) as number;
  }

  set m10(value: number) {
    this.#view.setFloat32(40, value as any, littleEndian);
  }

  get m14(): number {
    return this.#view.getFloat32(44, littleEndian) as number;
  }

  set m14(value: number) {
    this.#view.setFloat32(44, value as any, littleEndian);
  }

  get m3(): number {
    return this.#view.getFloat32(48, littleEndian) as number;
  }

  set m3(value: number) {
    this.#view.setFloat32(48, value as any, littleEndian);
  }

  get m7(): number {
    return this.#view.getFloat32(52, littleEndian) as number;
  }

  set m7(value: number) {
    this.#view.setFloat32(52, value as any, littleEndian);
  }

  get m11(): number {
    return this.#view.getFloat32(56, littleEndian) as number;
  }

  set m11(value: number) {
    this.#view.setFloat32(56, value as any, littleEndian);
  }

  get m15(): number {
    return this.#view.getFloat32(60, littleEndian) as number;
  }

  set m15(value: number) {
    this.#view.setFloat32(60, value as any, littleEndian);
  }
}

export class Color {
  static readonly SIZE = 4;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(options: Partial<{ r: number; g: number; b: number; a: number }>);
  constructor(r: number, g: number, b: number, a: number);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ r: number; g: number; b: number; a: number }>
      | number,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Color.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).r !== undefined) this.r = (arg0 as any).r;
      if ((arg0 as any).g !== undefined) this.g = (arg0 as any).g;
      if ((arg0 as any).b !== undefined) this.b = (arg0 as any).b;
      if ((arg0 as any).a !== undefined) this.a = (arg0 as any).a;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.r = args[0] as any;
    if (args[1] !== undefined) this.g = args[1] as any;
    if (args[2] !== undefined) this.b = args[2] as any;
    if (args[3] !== undefined) this.a = args[3] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Color {
    return new Color(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Color.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get r(): number {
    return this.#view.getUint8(0);
  }

  set r(value: number) {
    this.#view.setUint8(0, value);
  }

  get g(): number {
    return this.#view.getUint8(1);
  }

  set g(value: number) {
    this.#view.setUint8(1, value);
  }

  get b(): number {
    return this.#view.getUint8(2);
  }

  set b(value: number) {
    this.#view.setUint8(2, value);
  }

  get a(): number {
    return this.#view.getUint8(3);
  }

  set a(value: number) {
    this.#view.setUint8(3, value);
  }
}

export class Rectangle {
  static readonly SIZE = 16;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<{ x: number; y: number; width: number; height: number }>,
  );
  constructor(x: number, y: number, width: number, height: number);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ x: number; y: number; width: number; height: number }>
      | number,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Rectangle.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).x !== undefined) this.x = (arg0 as any).x;
      if ((arg0 as any).y !== undefined) this.y = (arg0 as any).y;
      if ((arg0 as any).width !== undefined) this.width = (arg0 as any).width;
      if ((arg0 as any).height !== undefined) {
        this.height = (arg0 as any).height;
      }
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.x = args[0] as any;
    if (args[1] !== undefined) this.y = args[1] as any;
    if (args[2] !== undefined) this.width = args[2] as any;
    if (args[3] !== undefined) this.height = args[3] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Rectangle {
    return new Rectangle(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Rectangle.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get x(): number {
    return this.#view.getFloat32(0, littleEndian) as number;
  }

  set x(value: number) {
    this.#view.setFloat32(0, value as any, littleEndian);
  }

  get y(): number {
    return this.#view.getFloat32(4, littleEndian) as number;
  }

  set y(value: number) {
    this.#view.setFloat32(4, value as any, littleEndian);
  }

  get width(): number {
    return this.#view.getFloat32(8, littleEndian) as number;
  }

  set width(value: number) {
    this.#view.setFloat32(8, value as any, littleEndian);
  }

  get height(): number {
    return this.#view.getFloat32(12, littleEndian) as number;
  }

  set height(value: number) {
    this.#view.setFloat32(12, value as any, littleEndian);
  }
}

export class Image {
  static readonly SIZE = 24;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Image {
    return new Image(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Image.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get dataPtr(): bigint {
    return this.#view.getBigUint64(0, littleEndian);
  }

  set dataPtr(value: bigint) {
    this.#view.setBigUint64(0, value, littleEndian);
  }

  get width(): number {
    return this.#view.getInt32(8, littleEndian) as number;
  }

  set width(value: number) {
    this.#view.setInt32(8, value as any, littleEndian);
  }

  get height(): number {
    return this.#view.getInt32(12, littleEndian) as number;
  }

  set height(value: number) {
    this.#view.setInt32(12, value as any, littleEndian);
  }

  get mipmaps(): number {
    return this.#view.getInt32(16, littleEndian) as number;
  }

  set mipmaps(value: number) {
    this.#view.setInt32(16, value as any, littleEndian);
  }

  get format(): number {
    return this.#view.getInt32(20, littleEndian) as number;
  }

  set format(value: number) {
    this.#view.setInt32(20, value as any, littleEndian);
  }
}

export class Texture {
  static readonly SIZE = 20;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<
      {
        id: number;
        width: number;
        height: number;
        mipmaps: number;
        format: number;
      }
    >,
  );
  constructor(
    id: number,
    width: number,
    height: number,
    mipmaps: number,
    format: number,
  );
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<
        {
          id: number;
          width: number;
          height: number;
          mipmaps: number;
          format: number;
        }
      >
      | number,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Texture.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).id !== undefined) this.id = (arg0 as any).id;
      if ((arg0 as any).width !== undefined) this.width = (arg0 as any).width;
      if ((arg0 as any).height !== undefined) {
        this.height = (arg0 as any).height;
      }
      if ((arg0 as any).mipmaps !== undefined) {
        this.mipmaps = (arg0 as any).mipmaps;
      }
      if ((arg0 as any).format !== undefined) {
        this.format = (arg0 as any).format;
      }
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.id = args[0] as any;
    if (args[1] !== undefined) this.width = args[1] as any;
    if (args[2] !== undefined) this.height = args[2] as any;
    if (args[3] !== undefined) this.mipmaps = args[3] as any;
    if (args[4] !== undefined) this.format = args[4] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Texture {
    return new Texture(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Texture.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get id(): number {
    return this.#view.getUint32(0, littleEndian) as number;
  }

  set id(value: number) {
    this.#view.setUint32(0, value as any, littleEndian);
  }

  get width(): number {
    return this.#view.getInt32(4, littleEndian) as number;
  }

  set width(value: number) {
    this.#view.setInt32(4, value as any, littleEndian);
  }

  get height(): number {
    return this.#view.getInt32(8, littleEndian) as number;
  }

  set height(value: number) {
    this.#view.setInt32(8, value as any, littleEndian);
  }

  get mipmaps(): number {
    return this.#view.getInt32(12, littleEndian) as number;
  }

  set mipmaps(value: number) {
    this.#view.setInt32(12, value as any, littleEndian);
  }

  get format(): number {
    return this.#view.getInt32(16, littleEndian) as number;
  }

  set format(value: number) {
    this.#view.setInt32(16, value as any, littleEndian);
  }
}

export class RenderTexture {
  static readonly SIZE = 44;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<{ id: number; texture: Texture; depth: Texture }>,
  );
  constructor(id: number, texture: Texture, depth: Texture);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ id: number; texture: Texture; depth: Texture }>
      | number,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(RenderTexture.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).id !== undefined) this.id = (arg0 as any).id;
      if ((arg0 as any).texture !== undefined) {
        this.texture = (arg0 as any).texture;
      }
      if ((arg0 as any).depth !== undefined) this.depth = (arg0 as any).depth;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.id = args[0] as any;
    if (args[1] !== undefined) this.texture = args[1] as any;
    if (args[2] !== undefined) this.depth = args[2] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): RenderTexture {
    return new RenderTexture(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, RenderTexture.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get id(): number {
    return this.#view.getUint32(0, littleEndian) as number;
  }

  set id(value: number) {
    this.#view.setUint32(0, value as any, littleEndian);
  }

  get texture(): Texture {
    return Texture.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 4);
  }

  set texture(value: Texture) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 4,
      Texture.SIZE,
    );
    target.set(value.buffer);
  }

  get depth(): Texture {
    return Texture.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 24,
    );
  }

  set depth(value: Texture) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 24,
      Texture.SIZE,
    );
    target.set(value.buffer);
  }
}

export class NPatchInfo {
  static readonly SIZE = 36;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<
      {
        source: Rectangle;
        left: number;
        top: number;
        right: number;
        bottom: number;
        layout: number;
      }
    >,
  );
  constructor(
    source: Rectangle,
    left: number,
    top: number,
    right: number,
    bottom: number,
    layout: number,
  );
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<
        {
          source: Rectangle;
          left: number;
          top: number;
          right: number;
          bottom: number;
          layout: number;
        }
      >
      | Rectangle,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(NPatchInfo.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).source !== undefined) {
        this.source = (arg0 as any).source;
      }
      if ((arg0 as any).left !== undefined) this.left = (arg0 as any).left;
      if ((arg0 as any).top !== undefined) this.top = (arg0 as any).top;
      if ((arg0 as any).right !== undefined) this.right = (arg0 as any).right;
      if ((arg0 as any).bottom !== undefined) {
        this.bottom = (arg0 as any).bottom;
      }
      if ((arg0 as any).layout !== undefined) {
        this.layout = (arg0 as any).layout;
      }
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.source = args[0] as any;
    if (args[1] !== undefined) this.left = args[1] as any;
    if (args[2] !== undefined) this.top = args[2] as any;
    if (args[3] !== undefined) this.right = args[3] as any;
    if (args[4] !== undefined) this.bottom = args[4] as any;
    if (args[5] !== undefined) this.layout = args[5] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): NPatchInfo {
    return new NPatchInfo(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, NPatchInfo.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get source(): Rectangle {
    return Rectangle.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
    );
  }

  set source(value: Rectangle) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      Rectangle.SIZE,
    );
    target.set(value.buffer);
  }

  get left(): number {
    return this.#view.getInt32(16, littleEndian) as number;
  }

  set left(value: number) {
    this.#view.setInt32(16, value as any, littleEndian);
  }

  get top(): number {
    return this.#view.getInt32(20, littleEndian) as number;
  }

  set top(value: number) {
    this.#view.setInt32(20, value as any, littleEndian);
  }

  get right(): number {
    return this.#view.getInt32(24, littleEndian) as number;
  }

  set right(value: number) {
    this.#view.setInt32(24, value as any, littleEndian);
  }

  get bottom(): number {
    return this.#view.getInt32(28, littleEndian) as number;
  }

  set bottom(value: number) {
    this.#view.setInt32(28, value as any, littleEndian);
  }

  get layout(): number {
    return this.#view.getInt32(32, littleEndian) as number;
  }

  set layout(value: number) {
    this.#view.setInt32(32, value as any, littleEndian);
  }
}

export class GlyphInfo {
  static readonly SIZE = 40;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<
      {
        value: number;
        offsetX: number;
        offsetY: number;
        advanceX: number;
        image: Image;
      }
    >,
  );
  constructor(
    value: number,
    offsetX: number,
    offsetY: number,
    advanceX: number,
    image: Image,
  );
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<
        {
          value: number;
          offsetX: number;
          offsetY: number;
          advanceX: number;
          image: Image;
        }
      >
      | number,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(GlyphInfo.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).value !== undefined) this.value = (arg0 as any).value;
      if ((arg0 as any).offsetX !== undefined) {
        this.offsetX = (arg0 as any).offsetX;
      }
      if ((arg0 as any).offsetY !== undefined) {
        this.offsetY = (arg0 as any).offsetY;
      }
      if ((arg0 as any).advanceX !== undefined) {
        this.advanceX = (arg0 as any).advanceX;
      }
      if ((arg0 as any).image !== undefined) this.image = (arg0 as any).image;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.value = args[0] as any;
    if (args[1] !== undefined) this.offsetX = args[1] as any;
    if (args[2] !== undefined) this.offsetY = args[2] as any;
    if (args[3] !== undefined) this.advanceX = args[3] as any;
    if (args[4] !== undefined) this.image = args[4] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): GlyphInfo {
    return new GlyphInfo(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, GlyphInfo.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get value(): number {
    return this.#view.getInt32(0, littleEndian) as number;
  }

  set value(value: number) {
    this.#view.setInt32(0, value as any, littleEndian);
  }

  get offsetX(): number {
    return this.#view.getInt32(4, littleEndian) as number;
  }

  set offsetX(value: number) {
    this.#view.setInt32(4, value as any, littleEndian);
  }

  get offsetY(): number {
    return this.#view.getInt32(8, littleEndian) as number;
  }

  set offsetY(value: number) {
    this.#view.setInt32(8, value as any, littleEndian);
  }

  get advanceX(): number {
    return this.#view.getInt32(12, littleEndian) as number;
  }

  set advanceX(value: number) {
    this.#view.setInt32(12, value as any, littleEndian);
  }

  get image(): Image {
    return Image.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 16);
  }

  set image(value: Image) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 16,
      Image.SIZE,
    );
    target.set(value.buffer);
  }
}

export class Font {
  static readonly SIZE = 48;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Font {
    return new Font(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Font.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get baseSize(): number {
    return this.#view.getInt32(0, littleEndian) as number;
  }

  set baseSize(value: number) {
    this.#view.setInt32(0, value as any, littleEndian);
  }

  get glyphCount(): number {
    return this.#view.getInt32(4, littleEndian) as number;
  }

  set glyphCount(value: number) {
    this.#view.setInt32(4, value as any, littleEndian);
  }

  get glyphPadding(): number {
    return this.#view.getInt32(8, littleEndian) as number;
  }

  set glyphPadding(value: number) {
    this.#view.setInt32(8, value as any, littleEndian);
  }

  get texture(): Texture {
    return Texture.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
    );
  }

  set texture(value: Texture) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
      Texture.SIZE,
    );
    target.set(value.buffer);
  }

  get recsPtr(): bigint {
    return this.#view.getBigUint64(32, littleEndian);
  }

  set recsPtr(value: bigint) {
    this.#view.setBigUint64(32, value, littleEndian);
  }

  get glyphsPtr(): bigint {
    return this.#view.getBigUint64(40, littleEndian);
  }

  set glyphsPtr(value: bigint) {
    this.#view.setBigUint64(40, value, littleEndian);
  }
}

export class Camera3D {
  static readonly SIZE = 44;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<
      {
        position: Vector3;
        target: Vector3;
        up: Vector3;
        fovy: number;
        projection: number;
      }
    >,
  );
  constructor(
    position: Vector3,
    target: Vector3,
    up: Vector3,
    fovy: number,
    projection: number,
  );
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<
        {
          position: Vector3;
          target: Vector3;
          up: Vector3;
          fovy: number;
          projection: number;
        }
      >
      | Vector3,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Camera3D.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).position !== undefined) {
        this.position = (arg0 as any).position;
      }
      if ((arg0 as any).target !== undefined) {
        this.target = (arg0 as any).target;
      }
      if ((arg0 as any).up !== undefined) this.up = (arg0 as any).up;
      if ((arg0 as any).fovy !== undefined) this.fovy = (arg0 as any).fovy;
      if ((arg0 as any).projection !== undefined) {
        this.projection = (arg0 as any).projection;
      }
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.position = args[0] as any;
    if (args[1] !== undefined) this.target = args[1] as any;
    if (args[2] !== undefined) this.up = args[2] as any;
    if (args[3] !== undefined) this.fovy = args[3] as any;
    if (args[4] !== undefined) this.projection = args[4] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Camera3D {
    return new Camera3D(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Camera3D.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get position(): Vector3 {
    return Vector3.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 0);
  }

  set position(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }

  get target(): Vector3 {
    return Vector3.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
    );
  }

  set target(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }

  get up(): Vector3 {
    return Vector3.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 24,
    );
  }

  set up(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 24,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }

  get fovy(): number {
    return this.#view.getFloat32(36, littleEndian) as number;
  }

  set fovy(value: number) {
    this.#view.setFloat32(36, value as any, littleEndian);
  }

  get projection(): number {
    return this.#view.getInt32(40, littleEndian) as number;
  }

  set projection(value: number) {
    this.#view.setInt32(40, value as any, littleEndian);
  }
}

export class Camera2D {
  static readonly SIZE = 24;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<
      { offset: Vector2; target: Vector2; rotation: number; zoom: number }
    >,
  );
  constructor(offset: Vector2, target: Vector2, rotation: number, zoom: number);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<
        { offset: Vector2; target: Vector2; rotation: number; zoom: number }
      >
      | Vector2,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Camera2D.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).offset !== undefined) {
        this.offset = (arg0 as any).offset;
      }
      if ((arg0 as any).target !== undefined) {
        this.target = (arg0 as any).target;
      }
      if ((arg0 as any).rotation !== undefined) {
        this.rotation = (arg0 as any).rotation;
      }
      if ((arg0 as any).zoom !== undefined) this.zoom = (arg0 as any).zoom;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.offset = args[0] as any;
    if (args[1] !== undefined) this.target = args[1] as any;
    if (args[2] !== undefined) this.rotation = args[2] as any;
    if (args[3] !== undefined) this.zoom = args[3] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Camera2D {
    return new Camera2D(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Camera2D.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get offset(): Vector2 {
    return Vector2.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 0);
  }

  set offset(value: Vector2) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      Vector2.SIZE,
    );
    target.set(value.buffer);
  }

  get target(): Vector2 {
    return Vector2.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 8);
  }

  set target(value: Vector2) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 8,
      Vector2.SIZE,
    );
    target.set(value.buffer);
  }

  get rotation(): number {
    return this.#view.getFloat32(16, littleEndian) as number;
  }

  set rotation(value: number) {
    this.#view.setFloat32(16, value as any, littleEndian);
  }

  get zoom(): number {
    return this.#view.getFloat32(20, littleEndian) as number;
  }

  set zoom(value: number) {
    this.#view.setFloat32(20, value as any, littleEndian);
  }
}

export class Mesh {
  static readonly SIZE = 120;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Mesh {
    return new Mesh(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Mesh.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get vertexCount(): number {
    return this.#view.getInt32(0, littleEndian) as number;
  }

  set vertexCount(value: number) {
    this.#view.setInt32(0, value as any, littleEndian);
  }

  get triangleCount(): number {
    return this.#view.getInt32(4, littleEndian) as number;
  }

  set triangleCount(value: number) {
    this.#view.setInt32(4, value as any, littleEndian);
  }

  get verticesPtr(): bigint {
    return this.#view.getBigUint64(8, littleEndian);
  }

  set verticesPtr(value: bigint) {
    this.#view.setBigUint64(8, value, littleEndian);
  }

  get texcoordsPtr(): bigint {
    return this.#view.getBigUint64(16, littleEndian);
  }

  set texcoordsPtr(value: bigint) {
    this.#view.setBigUint64(16, value, littleEndian);
  }

  get texcoords2Ptr(): bigint {
    return this.#view.getBigUint64(24, littleEndian);
  }

  set texcoords2Ptr(value: bigint) {
    this.#view.setBigUint64(24, value, littleEndian);
  }

  get normalsPtr(): bigint {
    return this.#view.getBigUint64(32, littleEndian);
  }

  set normalsPtr(value: bigint) {
    this.#view.setBigUint64(32, value, littleEndian);
  }

  get tangentsPtr(): bigint {
    return this.#view.getBigUint64(40, littleEndian);
  }

  set tangentsPtr(value: bigint) {
    this.#view.setBigUint64(40, value, littleEndian);
  }

  get colorsPtr(): bigint {
    return this.#view.getBigUint64(48, littleEndian);
  }

  set colorsPtr(value: bigint) {
    this.#view.setBigUint64(48, value, littleEndian);
  }

  get indicesPtr(): bigint {
    return this.#view.getBigUint64(56, littleEndian);
  }

  set indicesPtr(value: bigint) {
    this.#view.setBigUint64(56, value, littleEndian);
  }

  get boneCount(): number {
    return this.#view.getInt32(64, littleEndian) as number;
  }

  set boneCount(value: number) {
    this.#view.setInt32(64, value as any, littleEndian);
  }

  get boneIndicesPtr(): bigint {
    return this.#view.getBigUint64(72, littleEndian);
  }

  set boneIndicesPtr(value: bigint) {
    this.#view.setBigUint64(72, value, littleEndian);
  }

  get boneWeightsPtr(): bigint {
    return this.#view.getBigUint64(80, littleEndian);
  }

  set boneWeightsPtr(value: bigint) {
    this.#view.setBigUint64(80, value, littleEndian);
  }

  get animVerticesPtr(): bigint {
    return this.#view.getBigUint64(88, littleEndian);
  }

  set animVerticesPtr(value: bigint) {
    this.#view.setBigUint64(88, value, littleEndian);
  }

  get animNormalsPtr(): bigint {
    return this.#view.getBigUint64(96, littleEndian);
  }

  set animNormalsPtr(value: bigint) {
    this.#view.setBigUint64(96, value, littleEndian);
  }

  get vaoId(): number {
    return this.#view.getUint32(104, littleEndian) as number;
  }

  set vaoId(value: number) {
    this.#view.setUint32(104, value as any, littleEndian);
  }

  get vboIdPtr(): bigint {
    return this.#view.getBigUint64(112, littleEndian);
  }

  set vboIdPtr(value: bigint) {
    this.#view.setBigUint64(112, value, littleEndian);
  }
}

export class Shader {
  static readonly SIZE = 16;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Shader {
    return new Shader(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Shader.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get id(): number {
    return this.#view.getUint32(0, littleEndian) as number;
  }

  set id(value: number) {
    this.#view.setUint32(0, value as any, littleEndian);
  }

  get locsPtr(): bigint {
    return this.#view.getBigUint64(8, littleEndian);
  }

  set locsPtr(value: bigint) {
    this.#view.setBigUint64(8, value, littleEndian);
  }
}

export class MaterialMap {
  static readonly SIZE = 28;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<{ texture: Texture; color: Color; value: number }>,
  );
  constructor(texture: Texture, color: Color, value: number);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ texture: Texture; color: Color; value: number }>
      | Texture,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(MaterialMap.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).texture !== undefined) {
        this.texture = (arg0 as any).texture;
      }
      if ((arg0 as any).color !== undefined) this.color = (arg0 as any).color;
      if ((arg0 as any).value !== undefined) this.value = (arg0 as any).value;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.texture = args[0] as any;
    if (args[1] !== undefined) this.color = args[1] as any;
    if (args[2] !== undefined) this.value = args[2] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): MaterialMap {
    return new MaterialMap(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, MaterialMap.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get texture(): Texture {
    return Texture.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 0);
  }

  set texture(value: Texture) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      Texture.SIZE,
    );
    target.set(value.buffer);
  }

  get color(): Color {
    return Color.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 20);
  }

  set color(value: Color) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 20,
      Color.SIZE,
    );
    target.set(value.buffer);
  }

  get value(): number {
    return this.#view.getFloat32(24, littleEndian) as number;
  }

  set value(value: number) {
    this.#view.setFloat32(24, value as any, littleEndian);
  }
}

export class Material {
  static readonly SIZE = 40;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Material {
    return new Material(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Material.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get shader(): Shader {
    return Shader.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 0);
  }

  set shader(value: Shader) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      Shader.SIZE,
    );
    target.set(value.buffer);
  }

  get mapsPtr(): bigint {
    return this.#view.getBigUint64(16, littleEndian);
  }

  set mapsPtr(value: bigint) {
    this.#view.setBigUint64(16, value, littleEndian);
  }

  get params(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 24,
      4,
    );
  }

  set params(values: ArrayLike<number>) {
    const view = this.params;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }
}

export class Transform {
  static readonly SIZE = 40;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<
      { translation: Vector3; rotation: Vector4; scale: Vector3 }
    >,
  );
  constructor(translation: Vector3, rotation: Vector4, scale: Vector3);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ translation: Vector3; rotation: Vector4; scale: Vector3 }>
      | Vector3,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Transform.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).translation !== undefined) {
        this.translation = (arg0 as any).translation;
      }
      if ((arg0 as any).rotation !== undefined) {
        this.rotation = (arg0 as any).rotation;
      }
      if ((arg0 as any).scale !== undefined) this.scale = (arg0 as any).scale;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.translation = args[0] as any;
    if (args[1] !== undefined) this.rotation = args[1] as any;
    if (args[2] !== undefined) this.scale = args[2] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Transform {
    return new Transform(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Transform.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get translation(): Vector3 {
    return Vector3.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 0);
  }

  set translation(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }

  get rotation(): Vector4 {
    return Vector4.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
    );
  }

  set rotation(value: Vector4) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
      Vector4.SIZE,
    );
    target.set(value.buffer);
  }

  get scale(): Vector3 {
    return Vector3.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 28,
    );
  }

  set scale(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 28,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }
}

export class BoneInfo {
  static readonly SIZE = 36;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): BoneInfo {
    return new BoneInfo(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, BoneInfo.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get name(): string {
    const bytes = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      32,
    );
    let end = bytes.indexOf(0);
    if (end === -1) end = 32;
    return new TextDecoder().decode(bytes.subarray(0, end));
  }

  set name(value: string) {
    const bytes = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      32,
    );
    bytes.fill(0);
    const encoded = new TextEncoder().encode(value);
    bytes.set(encoded.subarray(0, 32));
  }

  get nameBytes(): Uint8Array {
    return new Uint8Array(this.#buffer.buffer, this.#buffer.byteOffset + 0, 32);
  }

  get parent(): number {
    return this.#view.getInt32(32, littleEndian) as number;
  }

  set parent(value: number) {
    this.#view.setInt32(32, value as any, littleEndian);
  }
}

export class ModelSkeleton {
  static readonly SIZE = 24;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): ModelSkeleton {
    return new ModelSkeleton(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, ModelSkeleton.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get boneCount(): number {
    return this.#view.getInt32(0, littleEndian) as number;
  }

  set boneCount(value: number) {
    this.#view.setInt32(0, value as any, littleEndian);
  }

  get bonesPtr(): bigint {
    return this.#view.getBigUint64(8, littleEndian);
  }

  set bonesPtr(value: bigint) {
    this.#view.setBigUint64(8, value, littleEndian);
  }

  get bindPosePtr(): bigint {
    return this.#view.getBigUint64(16, littleEndian);
  }

  set bindPosePtr(value: bigint) {
    this.#view.setBigUint64(16, value, littleEndian);
  }
}

export class Model {
  static readonly SIZE = 136;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Model {
    return new Model(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Model.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get transform(): Matrix {
    return Matrix.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 0);
  }

  set transform(value: Matrix) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      Matrix.SIZE,
    );
    target.set(value.buffer);
  }

  get meshCount(): number {
    return this.#view.getInt32(64, littleEndian) as number;
  }

  set meshCount(value: number) {
    this.#view.setInt32(64, value as any, littleEndian);
  }

  get materialCount(): number {
    return this.#view.getInt32(68, littleEndian) as number;
  }

  set materialCount(value: number) {
    this.#view.setInt32(68, value as any, littleEndian);
  }

  get meshesPtr(): bigint {
    return this.#view.getBigUint64(72, littleEndian);
  }

  set meshesPtr(value: bigint) {
    this.#view.setBigUint64(72, value, littleEndian);
  }

  get materialsPtr(): bigint {
    return this.#view.getBigUint64(80, littleEndian);
  }

  set materialsPtr(value: bigint) {
    this.#view.setBigUint64(80, value, littleEndian);
  }

  get meshMaterialPtr(): bigint {
    return this.#view.getBigUint64(88, littleEndian);
  }

  set meshMaterialPtr(value: bigint) {
    this.#view.setBigUint64(88, value, littleEndian);
  }

  get skeleton(): ModelSkeleton {
    return ModelSkeleton.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 96,
    );
  }

  set skeleton(value: ModelSkeleton) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 96,
      ModelSkeleton.SIZE,
    );
    target.set(value.buffer);
  }

  get currentPosePtr(): bigint {
    return this.#view.getBigUint64(120, littleEndian);
  }

  set currentPosePtr(value: bigint) {
    this.#view.setBigUint64(120, value, littleEndian);
  }

  get boneMatricesPtr(): bigint {
    return this.#view.getBigUint64(128, littleEndian);
  }

  set boneMatricesPtr(value: bigint) {
    this.#view.setBigUint64(128, value, littleEndian);
  }
}

export class ModelAnimation {
  static readonly SIZE = 48;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): ModelAnimation {
    return new ModelAnimation(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, ModelAnimation.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get name(): string {
    const bytes = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      32,
    );
    let end = bytes.indexOf(0);
    if (end === -1) end = 32;
    return new TextDecoder().decode(bytes.subarray(0, end));
  }

  set name(value: string) {
    const bytes = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      32,
    );
    bytes.fill(0);
    const encoded = new TextEncoder().encode(value);
    bytes.set(encoded.subarray(0, 32));
  }

  get nameBytes(): Uint8Array {
    return new Uint8Array(this.#buffer.buffer, this.#buffer.byteOffset + 0, 32);
  }

  get boneCount(): number {
    return this.#view.getInt32(32, littleEndian) as number;
  }

  set boneCount(value: number) {
    this.#view.setInt32(32, value as any, littleEndian);
  }

  get keyframeCount(): number {
    return this.#view.getInt32(36, littleEndian) as number;
  }

  set keyframeCount(value: number) {
    this.#view.setInt32(36, value as any, littleEndian);
  }

  get keyframePosesPtr(): bigint {
    return this.#view.getBigUint64(40, littleEndian);
  }

  set keyframePosesPtr(value: bigint) {
    this.#view.setBigUint64(40, value, littleEndian);
  }
}

export class Ray {
  static readonly SIZE = 24;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(options: Partial<{ position: Vector3; direction: Vector3 }>);
  constructor(position: Vector3, direction: Vector3);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ position: Vector3; direction: Vector3 }>
      | Vector3,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Ray.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).position !== undefined) {
        this.position = (arg0 as any).position;
      }
      if ((arg0 as any).direction !== undefined) {
        this.direction = (arg0 as any).direction;
      }
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.position = args[0] as any;
    if (args[1] !== undefined) this.direction = args[1] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Ray {
    return new Ray(new Uint8Array(buffer as ArrayBuffer, byteOffset, Ray.SIZE));
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get position(): Vector3 {
    return Vector3.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 0);
  }

  set position(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }

  get direction(): Vector3 {
    return Vector3.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
    );
  }

  set direction(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }
}

export class RayCollision {
  static readonly SIZE = 32;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(
    options: Partial<
      { hit: boolean; distance: number; point: Vector3; normal: Vector3 }
    >,
  );
  constructor(hit: boolean, distance: number, point: Vector3, normal: Vector3);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<
        { hit: boolean; distance: number; point: Vector3; normal: Vector3 }
      >
      | boolean,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(RayCollision.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).hit !== undefined) this.hit = (arg0 as any).hit;
      if ((arg0 as any).distance !== undefined) {
        this.distance = (arg0 as any).distance;
      }
      if ((arg0 as any).point !== undefined) this.point = (arg0 as any).point;
      if ((arg0 as any).normal !== undefined) {
        this.normal = (arg0 as any).normal;
      }
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.hit = args[0] as any;
    if (args[1] !== undefined) this.distance = args[1] as any;
    if (args[2] !== undefined) this.point = args[2] as any;
    if (args[3] !== undefined) this.normal = args[3] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): RayCollision {
    return new RayCollision(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, RayCollision.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get hit(): boolean {
    return this.#view.getUint8(0) !== 0;
  }

  set hit(value: boolean) {
    this.#view.setUint8(0, value ? 1 : 0);
  }

  get distance(): number {
    return this.#view.getFloat32(4, littleEndian) as number;
  }

  set distance(value: number) {
    this.#view.setFloat32(4, value as any, littleEndian);
  }

  get point(): Vector3 {
    return Vector3.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 8);
  }

  set point(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 8,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }

  get normal(): Vector3 {
    return Vector3.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 20,
    );
  }

  set normal(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 20,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }
}

export class BoundingBox {
  static readonly SIZE = 24;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(options: Partial<{ min: Vector3; max: Vector3 }>);
  constructor(min: Vector3, max: Vector3);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ min: Vector3; max: Vector3 }>
      | Vector3,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(BoundingBox.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).min !== undefined) this.min = (arg0 as any).min;
      if ((arg0 as any).max !== undefined) this.max = (arg0 as any).max;
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.min = args[0] as any;
    if (args[1] !== undefined) this.max = args[1] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): BoundingBox {
    return new BoundingBox(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, BoundingBox.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get min(): Vector3 {
    return Vector3.fromBuffer(this.#buffer.buffer, this.#buffer.byteOffset + 0);
  }

  set min(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }

  get max(): Vector3 {
    return Vector3.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
    );
  }

  set max(value: Vector3) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 12,
      Vector3.SIZE,
    );
    target.set(value.buffer);
  }
}

export class Wave {
  static readonly SIZE = 24;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Wave {
    return new Wave(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Wave.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get frameCount(): number {
    return this.#view.getUint32(0, littleEndian) as number;
  }

  set frameCount(value: number) {
    this.#view.setUint32(0, value as any, littleEndian);
  }

  get sampleRate(): number {
    return this.#view.getUint32(4, littleEndian) as number;
  }

  set sampleRate(value: number) {
    this.#view.setUint32(4, value as any, littleEndian);
  }

  get sampleSize(): number {
    return this.#view.getUint32(8, littleEndian) as number;
  }

  set sampleSize(value: number) {
    this.#view.setUint32(8, value as any, littleEndian);
  }

  get channels(): number {
    return this.#view.getUint32(12, littleEndian) as number;
  }

  set channels(value: number) {
    this.#view.setUint32(12, value as any, littleEndian);
  }

  get dataPtr(): bigint {
    return this.#view.getBigUint64(16, littleEndian);
  }

  set dataPtr(value: bigint) {
    this.#view.setBigUint64(16, value, littleEndian);
  }
}

export class AudioStream {
  static readonly SIZE = 32;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): AudioStream {
    return new AudioStream(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, AudioStream.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get bufferPtr(): bigint {
    return this.#view.getBigUint64(0, littleEndian);
  }

  set bufferPtr(value: bigint) {
    this.#view.setBigUint64(0, value, littleEndian);
  }

  get processorPtr(): bigint {
    return this.#view.getBigUint64(8, littleEndian);
  }

  set processorPtr(value: bigint) {
    this.#view.setBigUint64(8, value, littleEndian);
  }

  get sampleRate(): number {
    return this.#view.getUint32(16, littleEndian) as number;
  }

  set sampleRate(value: number) {
    this.#view.setUint32(16, value as any, littleEndian);
  }

  get sampleSize(): number {
    return this.#view.getUint32(20, littleEndian) as number;
  }

  set sampleSize(value: number) {
    this.#view.setUint32(20, value as any, littleEndian);
  }

  get channels(): number {
    return this.#view.getUint32(24, littleEndian) as number;
  }

  set channels(value: number) {
    this.#view.setUint32(24, value as any, littleEndian);
  }
}

export class Sound {
  static readonly SIZE = 40;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>);
  constructor(options: Partial<{ stream: AudioStream; frameCount: number }>);
  constructor(stream: AudioStream, frameCount: number);
  constructor(
    arg0:
      | Uint8Array<ArrayBuffer>
      | Partial<{ stream: AudioStream; frameCount: number }>
      | AudioStream,
    ...rest: unknown[]
  ) {
    if (arg0 instanceof Uint8Array) {
      this.#buffer = arg0;
      this.#view = new DataView(
        this.#buffer.buffer,
        this.#buffer.byteOffset,
        this.#buffer.byteLength,
      );
      return;
    }
    this.#buffer = new Uint8Array(new ArrayBuffer(Sound.SIZE));
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
    if (arg0 && typeof arg0 === "object" && !("buffer" in (arg0 as object))) {
      if ((arg0 as any).stream !== undefined) {
        this.stream = (arg0 as any).stream;
      }
      if ((arg0 as any).frameCount !== undefined) {
        this.frameCount = (arg0 as any).frameCount;
      }
      return;
    }
    const args = [arg0, ...rest];
    if (args[0] !== undefined) this.stream = args[0] as any;
    if (args[1] !== undefined) this.frameCount = args[1] as any;
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Sound {
    return new Sound(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Sound.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get stream(): AudioStream {
    return AudioStream.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
    );
  }

  set stream(value: AudioStream) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      AudioStream.SIZE,
    );
    target.set(value.buffer);
  }

  get frameCount(): number {
    return this.#view.getUint32(32, littleEndian) as number;
  }

  set frameCount(value: number) {
    this.#view.setUint32(32, value as any, littleEndian);
  }
}

export class Music {
  static readonly SIZE = 56;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): Music {
    return new Music(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, Music.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get stream(): AudioStream {
    return AudioStream.fromBuffer(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
    );
  }

  set stream(value: AudioStream) {
    const target = new Uint8Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      AudioStream.SIZE,
    );
    target.set(value.buffer);
  }

  get frameCount(): number {
    return this.#view.getUint32(32, littleEndian) as number;
  }

  set frameCount(value: number) {
    this.#view.setUint32(32, value as any, littleEndian);
  }

  get looping(): boolean {
    return this.#view.getUint8(36) !== 0;
  }

  set looping(value: boolean) {
    this.#view.setUint8(36, value ? 1 : 0);
  }

  get ctxType(): number {
    return this.#view.getInt32(40, littleEndian) as number;
  }

  set ctxType(value: number) {
    this.#view.setInt32(40, value as any, littleEndian);
  }

  get ctxDataPtr(): bigint {
    return this.#view.getBigUint64(48, littleEndian);
  }

  set ctxDataPtr(value: bigint) {
    this.#view.setBigUint64(48, value, littleEndian);
  }
}

export class VrDeviceInfo {
  static readonly SIZE = 60;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): VrDeviceInfo {
    return new VrDeviceInfo(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, VrDeviceInfo.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get hResolution(): number {
    return this.#view.getInt32(0, littleEndian) as number;
  }

  set hResolution(value: number) {
    this.#view.setInt32(0, value as any, littleEndian);
  }

  get vResolution(): number {
    return this.#view.getInt32(4, littleEndian) as number;
  }

  set vResolution(value: number) {
    this.#view.setInt32(4, value as any, littleEndian);
  }

  get hScreenSize(): number {
    return this.#view.getFloat32(8, littleEndian) as number;
  }

  set hScreenSize(value: number) {
    this.#view.setFloat32(8, value as any, littleEndian);
  }

  get vScreenSize(): number {
    return this.#view.getFloat32(12, littleEndian) as number;
  }

  set vScreenSize(value: number) {
    this.#view.setFloat32(12, value as any, littleEndian);
  }

  get eyeToScreenDistance(): number {
    return this.#view.getFloat32(16, littleEndian) as number;
  }

  set eyeToScreenDistance(value: number) {
    this.#view.setFloat32(16, value as any, littleEndian);
  }

  get lensSeparationDistance(): number {
    return this.#view.getFloat32(20, littleEndian) as number;
  }

  set lensSeparationDistance(value: number) {
    this.#view.setFloat32(20, value as any, littleEndian);
  }

  get interpupillaryDistance(): number {
    return this.#view.getFloat32(24, littleEndian) as number;
  }

  set interpupillaryDistance(value: number) {
    this.#view.setFloat32(24, value as any, littleEndian);
  }

  get lensDistortionValues(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 28,
      4,
    );
  }

  set lensDistortionValues(values: ArrayLike<number>) {
    const view = this.lensDistortionValues;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }

  get chromaAbCorrection(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 44,
      4,
    );
  }

  set chromaAbCorrection(values: ArrayLike<number>) {
    const view = this.chromaAbCorrection;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }
}

export class VrStereoConfig {
  static readonly SIZE = 304;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): VrStereoConfig {
    return new VrStereoConfig(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, VrStereoConfig.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get projection(): Matrix[] {
    const items: Matrix[] = [];
    const size = Matrix.SIZE;
    for (let i = 0; i < 2; i++) {
      items.push(
        Matrix.fromBuffer(
          this.#buffer.buffer,
          this.#buffer.byteOffset + 0 + i * size,
        ),
      );
    }
    return items;
  }

  set projection(values: Matrix[]) {
    const size = Matrix.SIZE;
    const count = Math.min(values.length, 2);
    for (let i = 0; i < count; i++) {
      const target = new Uint8Array(
        this.#buffer.buffer,
        this.#buffer.byteOffset + 0 + i * size,
        size,
      );
      target.set(values[i].buffer);
    }
  }

  get viewOffset(): Matrix[] {
    const items: Matrix[] = [];
    const size = Matrix.SIZE;
    for (let i = 0; i < 2; i++) {
      items.push(
        Matrix.fromBuffer(
          this.#buffer.buffer,
          this.#buffer.byteOffset + 128 + i * size,
        ),
      );
    }
    return items;
  }

  set viewOffset(values: Matrix[]) {
    const size = Matrix.SIZE;
    const count = Math.min(values.length, 2);
    for (let i = 0; i < count; i++) {
      const target = new Uint8Array(
        this.#buffer.buffer,
        this.#buffer.byteOffset + 128 + i * size,
        size,
      );
      target.set(values[i].buffer);
    }
  }

  get leftLensCenter(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 256,
      2,
    );
  }

  set leftLensCenter(values: ArrayLike<number>) {
    const view = this.leftLensCenter;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }

  get rightLensCenter(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 264,
      2,
    );
  }

  set rightLensCenter(values: ArrayLike<number>) {
    const view = this.rightLensCenter;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }

  get leftScreenCenter(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 272,
      2,
    );
  }

  set leftScreenCenter(values: ArrayLike<number>) {
    const view = this.leftScreenCenter;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }

  get rightScreenCenter(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 280,
      2,
    );
  }

  set rightScreenCenter(values: ArrayLike<number>) {
    const view = this.rightScreenCenter;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }

  get scale(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 288,
      2,
    );
  }

  set scale(values: ArrayLike<number>) {
    const view = this.scale;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }

  get scaleIn(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 296,
      2,
    );
  }

  set scaleIn(values: ArrayLike<number>) {
    const view = this.scaleIn;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }
}

export class FilePathList {
  static readonly SIZE = 16;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): FilePathList {
    return new FilePathList(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, FilePathList.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get count(): number {
    return this.#view.getUint32(0, littleEndian) as number;
  }

  set count(value: number) {
    this.#view.setUint32(0, value as any, littleEndian);
  }

  get pathsPtr(): bigint {
    return this.#view.getBigUint64(8, littleEndian);
  }

  set pathsPtr(value: bigint) {
    this.#view.setBigUint64(8, value, littleEndian);
  }
}

export class AutomationEvent {
  static readonly SIZE = 24;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): AutomationEvent {
    return new AutomationEvent(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, AutomationEvent.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get frame(): number {
    return this.#view.getUint32(0, littleEndian) as number;
  }

  set frame(value: number) {
    this.#view.setUint32(0, value as any, littleEndian);
  }

  get type(): number {
    return this.#view.getUint32(4, littleEndian) as number;
  }

  set type(value: number) {
    this.#view.setUint32(4, value as any, littleEndian);
  }

  get params(): Int32Array {
    return new Int32Array(this.#buffer.buffer, this.#buffer.byteOffset + 8, 4);
  }

  set params(values: ArrayLike<number>) {
    const view = this.params;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }
}

export class AutomationEventList {
  static readonly SIZE = 16;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(
    buffer: ArrayBufferLike,
    byteOffset = 0,
  ): AutomationEventList {
    return new AutomationEventList(
      new Uint8Array(
        buffer as ArrayBuffer,
        byteOffset,
        AutomationEventList.SIZE,
      ),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get capacity(): number {
    return this.#view.getUint32(0, littleEndian) as number;
  }

  set capacity(value: number) {
    this.#view.setUint32(0, value as any, littleEndian);
  }

  get count(): number {
    return this.#view.getUint32(4, littleEndian) as number;
  }

  set count(value: number) {
    this.#view.setUint32(4, value as any, littleEndian);
  }

  get eventsPtr(): bigint {
    return this.#view.getBigUint64(8, littleEndian);
  }

  set eventsPtr(value: bigint) {
    this.#view.setBigUint64(8, value, littleEndian);
  }
}

export class float3 {
  static readonly SIZE = 12;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): float3 {
    return new float3(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, float3.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get v(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      3,
    );
  }

  set v(values: ArrayLike<number>) {
    const view = this.v;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }
}

export class float16 {
  static readonly SIZE = 64;
  #buffer: Uint8Array<ArrayBuffer>;
  #view: DataView;

  constructor(buffer: Uint8Array<ArrayBuffer>) {
    this.#buffer = buffer;
    this.#view = new DataView(
      this.#buffer.buffer,
      this.#buffer.byteOffset,
      this.#buffer.byteLength,
    );
  }

  static fromBuffer(buffer: ArrayBufferLike, byteOffset = 0): float16 {
    return new float16(
      new Uint8Array(buffer as ArrayBuffer, byteOffset, float16.SIZE),
    );
  }

  get buffer(): Uint8Array<ArrayBuffer> {
    return this.#buffer;
  }

  get v(): Float32Array {
    return new Float32Array(
      this.#buffer.buffer,
      this.#buffer.byteOffset + 0,
      16,
    );
  }

  set v(values: ArrayLike<number>) {
    const view = this.v;
    const count = Math.min(values.length, view.length);
    for (let i = 0; i < count; i++) view[i] = values[i] as any;
  }
}
