// deno-lint-ignore-file no-explicit-any
// Generate ffi_structs.ts from raylib_api.json (Deno FFI struct layouts)

type Native = Deno.NativeType | "void";

const apiPath = new URL("./raylib_api.json", import.meta.url);
const api = JSON.parse(Deno.readTextFileSync(apiPath));

const aliasMap = new Map<string, string>(
  api.aliases.map((alias: { name: string; type: string }) => [
    alias.name,
    alias.type,
  ]),
);

const structMap = new Map<string, any>(
  api.structs.map((struct: any) => [struct.name, struct]),
);

const callbackSet = new Set<string>(api.callbacks.map((cb: any) => cb.name));

const primitiveMap: Record<string, Native> = {
  "void": "void",
  "bool": "u8",
  "char": "i8",
  "signed char": "i8",
  "unsigned char": "u8",
  "short": "i16",
  "unsigned short": "u16",
  "int": "i32",
  "unsigned int": "u32",
  "long": "i64",
  "unsigned long": "u64",
  "long long": "i64",
  "unsigned long long": "u64",
  "float": "f32",
  "double": "f64",
};

function resolveAlias(type: string): string {
  let current = type;
  const seen = new Set<string>();
  while (aliasMap.has(current) && !seen.has(current)) {
    seen.add(current);
    current = aliasMap.get(current)!;
  }
  return current;
}

function stripConst(type: string): string {
  return type.replace(/^const\s+/, "").trim();
}

function parseArray(type: string): { base: string; count: number } | null {
  const match = type.match(/^(.*)\[(\d+)\]$/);
  if (!match) return null;
  return { base: match[1].trim(), count: Number(match[2]) };
}

function flattenType(type: string, seen = new Set<string>()): Native[] {
  let t = type.trim();

  t = stripConst(t);

  const arrayMatch = t.match(/^(.*)\[(\d+)\]$/);
  if (arrayMatch) {
    const base = arrayMatch[1].trim();
    const count = Number(arrayMatch[2]);
    const inner = flattenType(base, seen);
    const out: Native[] = [];
    for (let i = 0; i < count; i++) out.push(...inner);
    return out;
  }

  if (t.includes("...")) return [];

  if (t.includes("*")) {
    if (/char\s*$/.test(t.replace(/\*/g, "").trim())) return ["buffer"];
    return ["pointer"];
  }

  t = resolveAlias(t);

  if (callbackSet.has(t)) return ["function"];

  const primitive = primitiveMap[t];
  if (primitive) return [primitive];

  const struct = structMap.get(t);
  if (struct) {
    if (seen.has(t)) return ["pointer"];
    seen.add(t);
    const fields: Native[] = [];
    for (const field of struct.fields) {
      fields.push(...flattenType(field.type, seen));
    }
    seen.delete(t);
    return fields;
  }

  return ["pointer"];
}

let out = "// This file is generated by generate_ffi_structs.ts\n\n";
out += "export const FFI_STRUCTS = {\n";
for (const struct of api.structs as any[]) {
  const flat = flattenType(struct.name);
  out += `  ${struct.name}: { struct: ${JSON.stringify(flat)} },\n`;
}

// Add entries for direct array-of-struct types used in the API.
const arrayStructTypes = new Map<string, string>();
const considerType = (type: string) => {
  const arrayInfo = parseArray(stripConst(type));
  if (!arrayInfo) return;
  const base = resolveAlias(arrayInfo.base);
  if (!structMap.has(base)) return;
  const key = `${base}[${arrayInfo.count}]`;
  const name = `${base}_${arrayInfo.count}`;
  arrayStructTypes.set(key, name);
};

for (const s of api.structs as any[]) {
  for (const field of s.fields ?? []) considerType(field.type);
}
for (const fn of api.functions as any[]) {
  for (const param of fn.params ?? []) considerType(param.type);
  considerType(fn.returnType);
}

for (const [key, name] of arrayStructTypes.entries()) {
  const flat = flattenType(key);
  out += `  ${name}: { struct: ${JSON.stringify(flat)} },\n`;
}

out += "} as const;\n";

const outputPath = new URL("./ffi_structs.ts", import.meta.url);
Deno.writeTextFileSync(outputPath, out);
