// deno-lint-ignore-file no-explicit-any
// Generate bindings.ts from raylib_api.json

type Native = Deno.NativeType | "void";

const apiPath = new URL("./raylib_api.json", import.meta.url);
const api = JSON.parse(Deno.readTextFileSync(apiPath));

const aliasMap = new Map<string, string>(
  api.aliases.map((alias: { name: string; type: string }) => [
    alias.name,
    alias.type,
  ]),
);

const structMap = new Map<string, any>(
  api.structs.map((struct: any) => [struct.name, struct]),
);

const callbackSet = new Set<string>(api.callbacks.map((cb: any) => cb.name));

const primitiveMap: Record<string, Native> = {
  "void": "void",
  "bool": "u8",
  "char": "i8",
  "signed char": "i8",
  "unsigned char": "u8",
  "short": "i16",
  "unsigned short": "u16",
  "int": "i32",
  "unsigned int": "u32",
  "long": "i64",
  "unsigned long": "u64",
  "long long": "i64",
  "unsigned long long": "u64",
  "float": "f32",
  "double": "f64",
};

function resolveAlias(type: string): string {
  let current = type;
  const seen = new Set<string>();
  while (aliasMap.has(current) && !seen.has(current)) {
    seen.add(current);
    current = aliasMap.get(current)!;
  }
  return current;
}

function starCount(type: string): number {
  return (type.match(/\*/g) ?? []).length;
}

function basePointerType(type: string): string {
  return type.replace(/\*/g, "").trim();
}

function flattenType(type: string, seen = new Set<string>()): Native[] {
  let t = type.trim();

  // strip const for resolution purposes
  t = t.replace(/^const\s+/, "").trim();

  const arrayMatch = t.match(/^(.*)\[(\d+)\]$/);
  if (arrayMatch) {
    const base = arrayMatch[1].trim();
    const count = Number(arrayMatch[2]);
    const inner = flattenType(base, seen);
    const out: Native[] = [];
    for (let i = 0; i < count; i++) out.push(...inner);
    return out;
  }

  if (t.includes("...")) return [];

  // pointers
  if (t.includes("*")) {
    const stars = starCount(t);
    const base = basePointerType(t);
    if (/char\s*$/.test(base)) return stars === 1 ? ["buffer"] : ["pointer"];
    const resolved = resolveAlias(base);
    if (stars === 1 && structMap.has(resolved)) return ["buffer"];
    return ["pointer"];
  }

  t = resolveAlias(t);

  if (callbackSet.has(t)) return ["function"];

  const primitive = primitiveMap[t];
  if (primitive) return [primitive];

  const struct = structMap.get(t);
  if (struct) {
    if (seen.has(t)) return ["pointer"];
    seen.add(t);
    const fields: Native[] = [];
    for (const field of struct.fields) {
      fields.push(...flattenType(field.type, seen));
    }
    seen.delete(t);
    return fields;
  }

  return ["pointer"];
}

function isDirectStruct(type: string): string | null {
  let t = type.trim();
  t = t.replace(/^const\s+/, "").trim();
  if (t.includes("...")) return null;
  const arrayMatch = t.match(/^(.*)\[(\d+)\]$/);
  if (arrayMatch) {
    const base = resolveAlias(arrayMatch[1].trim());
    const count = Number(arrayMatch[2]);
    if (structMap.has(base)) return `${base}_${count}`;
    return null;
  }
  if (t.includes("*")) return null;
  t = resolveAlias(t);
  if (callbackSet.has(t)) return null;
  if (structMap.has(t)) return t;
  return null;
}

function ffiTypeExpr(type: string, fnName?: string): string {
  if (fnName === "UnloadFontData" && type.trim() === "GlyphInfo *") {
    return JSON.stringify("pointer");
  }
  if (
    (fnName === "UnloadUTF8" || fnName === "UnloadFileText") &&
    type.trim() === "char *"
  ) {
    return JSON.stringify("pointer");
  }

  const direct = isDirectStruct(type);
  if (direct) return `FFI_STRUCTS.${direct}`;
  const flat = flattenType(type);
  if (flat.length === 0) return JSON.stringify("void");
  if (flat.length === 1) return JSON.stringify(flat[0]);
  return JSON.stringify({ struct: flat });
}

const getDefineValue = (name: string) =>
  api.defines.find((d: any) => d.name === name)?.value;

const disabledFunctions = new Set([
  "SetAudioStreamCallback",
]);

const major = getDefineValue("RAYLIB_VERSION_MAJOR");
const minor = getDefineValue("RAYLIB_VERSION_MINOR");
const patch = getDefineValue("RAYLIB_VERSION_PATCH");
const version = getDefineValue("RAYLIB_VERSION");

let result = "// This file is generated by generator.ts\n\n";
result += 'import { FFI_STRUCTS } from "./ffi_structs.ts";\n\n';

result += "// --- Version constants ---\n";
result += `export const RAYLIB_VERSION_MAJOR = ${major};\n`;
result += `export const RAYLIB_VERSION_MINOR = ${minor};\n`;
result += `export const RAYLIB_VERSION_PATCH = ${patch};\n`;
result += `export const RAYLIB_VERSION = ${JSON.stringify(version)};\n\n`;

result += `const DLL_TYPE = ({
  windows: "raylib.dll",
  linux: "libraylib.so",
  darwin: "libraylib.dylib",
} as Record<string, string>)[Deno.build.os];

export const lib = Deno.dlopen(
  "./blobs/" + DLL_TYPE,
  {\n`;

for (const fn of api.functions as any[]) {
  if (disabledFunctions.has(fn.name)) {
    result += `\t// Disabled: see main.ts audio stream probe.\n`;
    result += `\t// ${fn.name}: skipped,\n`;
    continue;
  }

  if (
    fn.returnType.includes("...") ||
    fn.params?.some((p: any) => p.type.includes("..."))
  ) {
    continue;
  }

  const parameters = (fn.params ?? []).map((param: any) =>
    ffiTypeExpr(param.type, fn.name)
  ).join(", ");

  result += `\t// ${fn.description ?? ""}\n`;
  result += `\t${fn.name}: { parameters: [${parameters}], result: ${
    ffiTypeExpr(fn.returnType, fn.name)
  } },\n`;
}

result += "  } as const,\n);\n\n";

result += "// Write the result to the bindings file\n";
const outputPath = new URL("../bindings.ts", import.meta.url);
Deno.writeTextFileSync(outputPath, result);
